// packages/ibm-products/src/components/PageHeader/next/PageHeaderTitleBreadcrumb.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React, { forwardRef } from 'react';
import classnames from 'classnames';
import { BreadcrumbItemProps, BreadcrumbItem } from '@carbon/react';
import { usePageHeader } from './context';
import { pkg } from '../../../settings';

export const PageHeaderTitleBreadcrumb = forwardRef<
  HTMLLIElement,
  BreadcrumbItemProps
>(({ className, children, ...other }, ref) => {
  const { titleClipped, refs } = usePageHeader();
  // Show title breadcrumb when:
  // 1. No content element exists (compact mode), OR
  // 2. Title is clipped and titleRef exists (with content element)
  const hasContentElement = refs?.contentRef?.current;
  const shouldShow = !hasContentElement || (titleClipped && !!refs?.titleRef);

  return (
    <BreadcrumbItem
      ref={ref}
      isCurrentPage
      {...other}
      className={classnames(
        className,
        `${pkg.prefix}--page-header-title-breadcrumb`,
        {
          [`${pkg.prefix}--page-header-title-breadcrumb-show`]: shouldShow,
          [`${pkg.prefix}--page-header-title-breadcrumb-show__with-content-element`]:
            hasContentElement,
          [`${pkg.prefix}--page-header-title-breadcrumb-show__without-content-element`]:
            !hasContentElement,
        }
      )}
    >
      {children}
    </BreadcrumbItem>
  );
});

PageHeaderTitleBreadcrumb.displayName = 'PageHeaderTitleBreadcrumb';

// packages/ibm-products-web-components/src/components/page-header/page-header-title-breadcrumb.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import { CDSBreadcrumbItem } from '@carbon/web-components/es/index';
import { prefix } from '../../globals/settings';
import styles from './page-header.scss?lit';

/**
 * Page header Title Breadcrumb
 * @element c4p-page-header-title-breadcrumb
 */
@customElement(`${prefix}-page-header-title-breadcrumb`)
class CDSPageHeaderTitleBreadcrumb extends CDSBreadcrumbItem {
  render() {
    return html`
      <cds-breadcrumb-item class="${prefix}--page-header-title-breadcrumb">
        <slot></slot>
      </cds-breadcrumb-item>
    `;
  }

  static styles = styles;
}

export default CDSPageHeaderTitleBreadcrumb;
