// packages/ibm-products-web-components/examples/create-full-page/src/components/create-influencer.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element';
import '@carbon/web-components/es/components/progress-indicator/index.js';

const blockClass = 'create-influencer';

export interface StepData {
  introStep?: boolean;
  secondaryLabel?: string;
  shouldIncludeStep?: boolean;
  title?: string;
  invalid?: boolean;
  disableSubmit?: boolean;
}

/**
 * CreateInfluencer component for web components
 */
@customElement('create-influencer')
export class CreateInfluencer extends LitElement {
  /**
   * Current step index (1-based)
   */
  @property({ type: Number, attribute: 'current-step' })
  currentStep = 1;

  /**
   * Step data array
   */
  @property({ type: Array, attribute: 'step-data' })
  stepData: StepData[] = [];

  /**
   * Influencer title
   */
  @property({ type: String })
  title = '';

  /**
   * Callback when a step is clicked
   */
  @property({ attribute: false })
  onClickStep?: (step: number) => void;

  // Disable shadow DOM to use Carbon styles
  createRenderRoot() {
    return this;
  }

  private getNumberOfDynamicStepsBeforeCurrentStep(
    array: StepData[],
    key: keyof StepData
  ): number {
    const dynamicSteps: StepData[] = [];
    array.forEach((item, index) => {
      if (item[key] === false && index <= this.currentStep - 1) {
        dynamicSteps.push(item);
      }
    });
    return dynamicSteps.length;
  }

  private handleStepChange(event: CustomEvent) {
    const newIndex = event.detail.index;
    if (this.onClickStep) {
      this.onClickStep(newIndex);
    }
  }

  private renderProgressSteps() {
    const extractedSteps = this.stepData?.filter((item) => !item?.introStep);
    const progressSteps = extractedSteps?.filter(
      (item) => item?.shouldIncludeStep !== false
    );

    // To get the ProgressIndicator's `currentIndex`, accounting for dynamic steps,
    // we need to subtract the number of !shouldIncludeStep/s before the current step
    const totalDynamicSteps =
      this.getNumberOfDynamicStepsBeforeCurrentStep(
        this.stepData,
        'shouldIncludeStep'
      ) || 0;

    const currentIndex =
      this.stepData[0]?.introStep
        ? this.currentStep - totalDynamicSteps - 2 // minus 2 because we need to account for the intro step
        : this.currentStep - totalDynamicSteps - 1; // minus 1 because ProgressIndicator currentIndex prop is 0 index based

    return html`
      <div class="${blockClass}__left-nav">
        ${this.title
          ? html`<h2 class="${blockClass}__title">${this.title}</h2>`
          : ''}
        ${this.currentStep === 1 && this.stepData[0]?.introStep
          ? ''
          : html`
              <cds-progress-indicator
                class="${blockClass}__progress-indicator"
                vertical
                space-equally
                current-index="${currentIndex}"
                @cds-progress-indicator-changed="${this.handleStepChange}"
              >
                ${progressSteps.map(
                  (step: StepData, stepIndex: number) => html`
                    <cds-progress-step
                      label="${step?.title || ''}"
                      secondary-label="${step.secondaryLabel || ''}"
                      ?invalid="${step.invalid}"
                    ></cds-progress-step>
                  `
                )}
              </cds-progress-indicator>
            `}
      </div>
    `;
  }

  render() {
    const classes = {
      [blockClass]: true,
    };

    return html`
      <div class="${classMap(classes)}">${this.renderProgressSteps()}</div>
    `;
  }
}

// packages/ibm-products/src/patterns/CreateFullPage/example/components/CreateInfluencer.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Import portions of React that are needed.
import React, { PropsWithChildren, ReactNode } from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { Heading, ProgressIndicator, ProgressStep } from '@carbon/react';

// The block part of our conventional BEM class names (blockClass__E--M).
const blockClass = 'create-influencer';
const componentName = 'CreateInfluencer';

interface Step {
  introStep?: boolean;
  secondaryLabel?: string;
  shouldIncludeStep?: boolean;
  title?: ReactNode;
}
interface CreateInfluencerProps {
  className?: string;
  currentStep: number;
  onClickStep?: (step: number) => void;
  stepData: Step[];
  title?: string | undefined;
}

export const CreateInfluencer = ({
  className,
  currentStep,
  onClickStep,
  stepData,
  title,
}: PropsWithChildren<CreateInfluencerProps>) => {
  const getNumberOfDynamicStepsBeforeCurrentStep = (array, key) => {
    const dynamicSteps: any[] = [];
    array.forEach((item, index) => {
      if (array[index]?.[key] === false && index <= currentStep - 1) {
        dynamicSteps.push(item);
      }
    });
    return dynamicSteps.length;
  };

  // renders the step progression components in the left influencer area
  const renderProgressSteps = () => {
    const extractedSteps = stepData?.filter((item) => !item?.introStep);
    const progressSteps = extractedSteps?.filter(
      (item) => item?.shouldIncludeStep
    );

    // To get the ProgressIndicator's `currentIndex`, accounting for dynamic steps,
    // we need to subtract the number of !shouldIncludeStep/s before the current step
    // which we get from `getNumberOfDynamicStepsBeforeCurrentStep()`
    const totalDynamicSteps =
      getNumberOfDynamicStepsBeforeCurrentStep(stepData, 'shouldIncludeStep') ||
      0;

    return (
      <div className={`${blockClass}__left-nav`}>
        {title && <Heading className={`${blockClass}__title`}>{title}</Heading>}
        {currentStep === 1 && stepData[0]?.introStep ? null : (
          <ProgressIndicator
            currentIndex={
              stepData[0]?.introStep
                ? currentStep - totalDynamicSteps - 2 // minus 2 because we need to account for the intro step in addition to `currentIndex` being 0 index based and our steps being 1 index based
                : currentStep - totalDynamicSteps - 1 // minus 1 because ProgressIndicator currentIndex prop is 0 index based, but our steps are 1 index based
            }
            spaceEqually
            vertical
            className={cx(`${blockClass}__progress-indicator`)}
            onChange={onClickStep}
          >
            {progressSteps.map((step: Step, stepIndex: number) => {
              return (
                <ProgressStep
                  label={step?.title as string}
                  key={stepIndex}
                  secondaryLabel={step.secondaryLabel || undefined}
                  invalid={(step as any).invalid}
                />
              );
            })}
          </ProgressIndicator>
        )}
      </div>
    );
  };

  return (
    <div className={cx(blockClass, className)}>{renderProgressSteps()}</div>
  );
};

CreateInfluencer.displayName = componentName;
