// packages/ibm-products/src/components/BigNumber/BigNumber.tsx
// @ts-check
/**
 * Copyright IBM Corp. 2024, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { forwardRef, ReactNode } from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';

import { getDevtoolsProps } from '../../global/js/utils/devtools';
import { getSupportedLocale } from '../../global/js/utils/getSupportedLocale';
import { pkg } from '../../settings';
import { ArrowUp, Information } from '@carbon/react/icons';
import { Tooltip } from '@carbon/react';
import { TooltipTrigger } from '../TooltipTrigger';
import { BigNumberSkeleton } from './BigNumberSkeleton';
import {
  BigNumberSizeValues,
  Characters,
  DefaultLocale,
  formatValue,
  getIconSize,
} from './constants';

const blockClass = `${pkg.prefix}--big-number`;
const componentName = 'BigNumber';

// NOTE: the component SCSS is not imported here: it is rolled up separately.

export interface BigNumberProps {
  className?: string;
  forceShowTotal?: boolean;
  fractionDigits?: number;
  iconButton?: ReactNode;
  loading?: boolean;
  label: string;
  locale?: string;
  percentage?: boolean;
  size?: BigNumberSizeValues;
  tooltipDescription?: string;
  total?: number;
  trending?: boolean;
  truncate?: boolean;
  value?: number;
}

/**
 * BigNumber is used to display large values in a small area. The display of
 * values can be the value itself, or grouped in a `numerator/denominator` fashion.
 * Control over the total fraction decimals displayed as well as how the
 * values/totals are displayed are done via a locale prop. Other optional props
 * allow control over size, truncation, if the value is a percentage, the addition
 * of a button as well as tool tip functionality.
 * The default locale is English (`en-US`) if one is not provided or if the provided one is not supported.
 */
export const BigNumber = forwardRef<HTMLElement, BigNumberProps>(
  (
    {
      // The component props, in alphabetical order (for consistency).
      className,
      forceShowTotal = false,
      fractionDigits = 1,
      iconButton,
      loading = false,
      label,
      locale = DefaultLocale,
      percentage = false,
      size = 'default',
      tooltipDescription,
      total,
      trending = false,
      truncate = true,
      value,
      // Collect any other property values passed in.
      ...rest
    },
    ref
  ) => {
    const bigNumberClasses = cx(className, {
      [`${blockClass}--lg`]: size === 'lg',
      [`${blockClass}--xl`]: size === 'xl',
    });

    const supportedLocale = getSupportedLocale(locale, DefaultLocale);

    const truncatedValue =
      formatValue(supportedLocale, value, fractionDigits, truncate) ??
      Characters.Dash;

    const truncatedTotal =
      formatValue(supportedLocale, total, fractionDigits, truncate) ??
      'Unknown';

    const shouldDisplayDenominator =
      forceShowTotal ||
      (!percentage &&
        total &&
        value &&
        total > value &&
        truncatedValue !== truncatedTotal);

    if (loading) {
      return (
        <BigNumberSkeleton
          {...rest}
          ref={ref}
          className={className}
          size={size}
          {...getDevtoolsProps(componentName)}
        />
      );
    }

    return (
      <figure
        {...rest}
        className={cx(blockClass, bigNumberClasses, className)}
        ref={ref}
        {...getDevtoolsProps(componentName)}
      >
        {/* Label and tooltip */}
        <span className={`${blockClass}__row`}>
          <figcaption className={`${blockClass}__label`}>{label}</figcaption>
          {tooltipDescription && (
            <Tooltip
              description={tooltipDescription}
              align="right"
              className={`${blockClass}__info`}
            >
              <TooltipTrigger className={`${blockClass}__tooltip-trigger`}>
                <Information size={16} />
              </TooltipTrigger>
            </Tooltip>
          )}
        </span>

        {/* Trending up arrow */}
        <span className={`${blockClass}__row`} role="math">
          {trending && (
            <ArrowUp
              className={`${blockClass}__trend`}
              size={getIconSize(size)}
            />
          )}

          {/* Numerator */}
          <span className={`${blockClass}__value`}>
            {percentage ? (
              <div className={`${blockClass}__percentage`}>
                {truncatedValue}
                <span className={`${blockClass}__percentage-mark`}>%</span>
              </div>
            ) : (
              truncatedValue
            )}
          </span>

          {/* Denominator */}
          {shouldDisplayDenominator && (
            <span className={`${blockClass}__total`}>
              <span>{`${Characters.Slash}${truncatedTotal}`}</span>
            </span>
          )}
          <span className={`${blockClass}__icon-button`}>{iconButton}</span>
        </span>
      </figure>
    );
  }
);

// The display name of the component, used by React. Note that displayName
// is used in preference to relying on function.name.
BigNumber.displayName = componentName;

// The types and DocGen commentary for the component props,
// in alphabetical order (for consistency).
// See https://www.npmjs.com/package/prop-types#usage.
BigNumber.propTypes = {
  /**
   * Provide an optional class to be applied to the containing node.
   */
  className: PropTypes.string,
  /**
   * The default behavior will hide `total` if `undefined` or is the same as `value`.
   *
   * Set to `true` to ignore the default behavior and show the `total`.
   */
  forceShowTotal: PropTypes.bool,
  /**
   * Specifies the number of fraction digits when truncating `value` and `total`.
   */
  fractionDigits: PropTypes.number,
  /**
   * Displays an icon button next to `value`.
   */
  iconButton: PropTypes.node,
  /**
   * Text label above the `value`.
   */
  label: PropTypes.string.isRequired,
  /**
   * When `true`, will show the loading state.
   */
  loading: PropTypes.bool,
  /**
   * Determines how `value` and `total` will be formatted.
   */
  locale: PropTypes.string,
  /**
   * Appends a percent sign (_%_) after `value` and hides `total`.
   */
  percentage: PropTypes.bool,
  /**
   *
   */
  size: PropTypes.oneOf(['default', 'lg', 'xl']),
  /**
   * When applied, an information icon will be rendered next to the
   * `label` and the description will be applied to its tooltip.
   */
  tooltipDescription: PropTypes.string,
  /**
   * The number that will appear after the slash (i.e. the "denominator" of a fraction).
   *
   * This number will not be rendered if it's the same as `value` or
   * `percentage` is true. See also the **forceShowTotal** prop.
   */
  total: PropTypes.number,
  /**
   * When `true`, will render a "trending up" icon.
   */
  trending: PropTypes.bool,
  /**
   * Abbreviates the number when `true`. E.g. from _1,000_ to _1K_.
   */
  truncate: PropTypes.bool,
  /**
   * The primary value to display (or the "numerator" of a fraction).
   */
  value: PropTypes.number,
};

// packages/ibm-products-web-components/src/components/big-number/big-number.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import { iconLoader } from '@carbon/web-components/es/globals/internal/icon-loader.js';
import { CarbonIcon } from '@carbon/web-components/es/globals/internal/icon-loader-utils';
import ArrowUp16 from '@carbon/icons/es/arrow--up/16';
import ArrowUp20 from '@carbon/icons/es/arrow--up/20';
import ArrowUp24 from '@carbon/icons/es/arrow--up/24';

import { prefix } from '../../globals/settings';
import { getSupportedLocale } from '../../globals/js/utils/getSupportedLocale';
import './big-number-skeleton';
import {
  BigNumberSize,
  BigNumberSizeValues,
  Characters,
  DefaultLocale,
  UNKNOWN,
} from './constants';
import styles from './big-number.scss?lit';

const blockClass = `${prefix}--big-number`;

/**
 * @element c4p-big-number
 * @slot label - Header area that displays the label above the value. This slot can be customized to include an info icon and a tooltip for additional context.
 * @slot trending-icon - Displays an icon indicating trend direction. Can be customized to show a downward arrow when the trend is not upward.
 * @slot icon-button - Displays an icon button next to `value`.
 */
@customElement(`${prefix}-big-number`)
class CDSBigNumber extends LitElement {
  @property({ type: Number, attribute: 'fraction-digits' })
  fractionDigits = 1;

  @property({ type: String })
  label: string | undefined;

  @property({ type: Boolean })
  loading = false;

  @property({ type: String })
  locale = DefaultLocale;

  @property({ type: Boolean })
  percentage = false;

  @property({ type: String })
  size: BigNumberSizeValues = BigNumberSize.Default;

  @property({ type: Number })
  total?: number;

  @property({ type: Boolean })
  trending = false;

  @property({ type: Boolean })
  truncate = true;

  @property({ type: Number })
  value?: number;

  private _formatValue(
    locale: Intl.LocalesArgument,
    value: number | null | undefined,
    fractionDigits: number,
    truncate: boolean
  ): string | null | undefined {
    if (value === null || value === undefined) {
      return null;
    }

    return truncate
      ? Intl.NumberFormat(locale, {
          notation: 'compact',
          minimumFractionDigits: fractionDigits,
          maximumFractionDigits: Math.round(fractionDigits),
        }).format(value)
      : Intl.NumberFormat(locale).format(value);
  }

  private _getTruncatedValue(
    value: number | undefined,
    placeholder: string
  ): string {
    const supportedLocale = getSupportedLocale(this.locale, DefaultLocale);
    const truncatedValue = this._formatValue(
      supportedLocale,
      value,
      this.fractionDigits,
      this.truncate
    );
    return truncatedValue ?? placeholder;
  }

  private _shouldDisplayDenominator(
    truncatedValue: string,
    truncatedTotal: string
  ): boolean {
    return (
      !this.percentage &&
      this.total !== undefined &&
      this.value !== undefined &&
      this.total > this.value &&
      truncatedValue !== truncatedTotal
    );
  }

  private _getTrendingIcon(): CarbonIcon {
    switch (this.size) {
      case BigNumberSize.Large:
        return ArrowUp20;
      case BigNumberSize.XLarge:
        return ArrowUp24;
      default:
        return ArrowUp16;
    }
  }

  render() {
    const { loading, label, percentage, size, total, trending, value } = this;

    const bigNumberClasses = classMap({
      [blockClass]: true,
      [`${blockClass}--lg`]: size === BigNumberSize.Large,
      [`${blockClass}--xl`]: size === BigNumberSize.XLarge,
    });

    const truncatedValue = this._getTruncatedValue(value, Characters.Dash);
    const truncatedTotal = this._getTruncatedValue(total, UNKNOWN);
    const shouldDisplayDenominator = this._shouldDisplayDenominator(
      truncatedValue,
      truncatedTotal
    );

    if (loading) {
      return html`
        <c4p-big-number-skeleton .size=${size}></c4p-big-number-skeleton>
      `;
    }

    return html`
      <figure class=${bigNumberClasses}>
        <!-- Label slot  -->
        <span class="${blockClass}__row">
          <slot name="label">
            <figcaption class="${blockClass}__label">${label}</figcaption>
          </slot>
        </span>
        <span class="${blockClass}__row" role="math">
          <!-- Trending up arrow  -->
          ${trending
            ? html`<slot name="trending-icon"
                >${iconLoader(this._getTrendingIcon(), {
                  slot: 'icon',
                  class: `${blockClass}__trend`,
                })}
              </slot>`
            : nothing}

          <!-- Numerator  -->
          <span class="${blockClass}__value">
            ${percentage
              ? html`<div class="${blockClass}__percentage">
                  ${truncatedValue}<span class="${blockClass}__percentage-mark"
                    >${Characters.Percentage}</span
                  >
                </div>`
              : truncatedValue}
          </span>

          <!-- Denominator -->
          ${shouldDisplayDenominator
            ? html`<span class="${blockClass}__total">
                <span>${`${Characters.Slash}${truncatedTotal}`}</span>
              </span>`
            : nothing}

          <!-- Icon button -->
          <span class="${blockClass}__icon-button">
            <slot name="icon-button"></slot>
          </span>
        </span>
      </figure>
    `;
  }

  static styles = styles;
}

export default CDSBigNumber;
