// packages/ibm-products/src/components/AddSelect/next/AddSelectColumn.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  useState,
  ChangeEvent,
} from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import {
  Search,
  Tag,
  Checkbox,
  type SearchProps,
  type TagProps,
  type CheckboxProps,
} from '@carbon/react';
import { blockClass, AddSelectContext } from './context';

/**
 * ----------------
 * AddSelectColumn
 * ----------------
 * A composable column component that wraps AddSelectRow items.
 * Provides optional search functionality with custom actions slot.
 * Lives inside AddSelectContent and can have multiple instances.
 */

export interface AddSelectColumnProps {
  /**
   * AddSelectRow children
   */
  children?: ReactNode;
  /**
   * Column title displayed in the header
   */
  title?: string;
  /**
   * Label text for the search input
   */
  searchLabel?: string;
  /**
   * Placeholder text for the search input
   */
  searchPlaceholder?: string;
  /**
   * Callback when search value changes
   */
  onSearch?: (value: string) => void;
  /**
   * Actions slot - adds custom actions (filter/sort) next to search
   */
  actionsSlot?: ReactNode;
  /**
   * Whether to hide the search input
   */
  hideSearch?: boolean;
  /**
   * Whether to enable multi-selection (checkboxes) or single selection (radio buttons)
   */
  multi?: boolean;
  /**
   * Whether to show the "Select All" checkbox (only applicable when multi is true)
   */
  showSelectAll?: boolean;
  /**
   * Total number of items in the column (for display in tag)
   */
  itemCount?: number;
  /**
   * Whether all items are currently selected
   */
  allSelected?: boolean;
  /**
   * Whether the "Select All" checkbox is in an indeterminate state
   */
  allIndeterminate?: boolean;
  /**
   * Callback when "Select All" is toggled
   */
  onSelectAll?: (checked: boolean) => void;
  /**
   * Callback when navigating to children
   */
  onNavigate?: (itemId: string, title: string, parentId: string) => void;
  /**
   * Optional class name
   */
  className?: string;
  /**
   * Additional props to pass to the Search component
   */
  searchProps?: Omit<
    SearchProps,
    'labelText' | 'placeholder' | 'size' | 'onChange' | 'value'
  >;
  /**
   * Additional props to pass to the Tag component
   */
  tagProps?: Omit<TagProps<'div'>, 'type' | 'size' | 'children'>;
  /**
   * Additional props to pass to the Checkbox component (Select All)
   */
  selectAllCheckboxProps?: Omit<
    CheckboxProps,
    'id' | 'className' | 'checked' | 'onChange' | 'labelText'
  >;
}

const AddSelectColumn = forwardRef<HTMLDivElement, AddSelectColumnProps>(
  (
    {
      children,
      title = '',
      searchLabel = 'Search',
      searchPlaceholder = 'Search',
      onSearch,
      actionsSlot,
      hideSearch = false,
      multi = false,
      showSelectAll = false,
      itemCount = 0,
      allSelected = false,
      allIndeterminate = false,
      onSelectAll,
      onNavigate,
      className,
      searchProps,
      tagProps,
      selectAllCheckboxProps,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const parentContext = React.useContext(AddSelectContext);
    const [searchTerm, setSearchTerm] = useState('');

    const handleSearch = (e: ChangeEvent<HTMLInputElement>) => {
      const value = e.target.value;
      setSearchTerm(value);
      onSearch?.(value);
    };

    const handleSelectAll = (
      _event: React.ChangeEvent<HTMLInputElement>,
      { checked }: { checked: boolean }
    ) => {
      onSelectAll?.(checked);
    };

    const columnClasses = cx(`${blockClass}-column`, className);

    // Merge parent context with column-specific onNavigate
    const columnContext = {
      ...parentContext,
      multi,
      onNavigate,
    };

    return (
      <AddSelectContext.Provider value={columnContext}>
        <div className={columnClasses} ref={ref} {...rest}>
          {/* Search with optional actions */}
          {!hideSearch && (
            <div
              className={cx(`${blockClass}-column__search`, {
                [`${blockClass}-column__search--with-actions`]: actionsSlot,
              })}
            >
              <div
                className={
                  actionsSlot ? `${blockClass}-column__search-input` : undefined
                }
              >
                <Search
                  labelText={searchLabel}
                  placeholder={searchPlaceholder}
                  size="md"
                  onChange={handleSearch}
                  value={searchTerm}
                  {...searchProps}
                />
              </div>
              {actionsSlot && (
                <div className={`${blockClass}-column__actions`}>
                  {actionsSlot}
                </div>
              )}
            </div>
          )}

          {/* Header with Select All */}
          {(showSelectAll || title) && (
            <div className={`${blockClass}-column__header`}>
              {showSelectAll && multi ? (
                <Checkbox
                  id={`select-all-${title}`}
                  className={`${blockClass}-column__select-all`}
                  checked={allSelected}
                  indeterminate={allIndeterminate}
                  onChange={handleSelectAll}
                  labelText={
                    <>
                      <span className={`${blockClass}-column__title`}>
                        {title}
                      </span>
                      {itemCount > 0 && (
                        <Tag type="gray" size="sm" {...tagProps}>
                          {itemCount}
                        </Tag>
                      )}
                    </>
                  }
                  {...selectAllCheckboxProps}
                />
              ) : (
                <div className={`${blockClass}-column__title-wrapper`}>
                  <span className={`${blockClass}-column__title`}>{title}</span>
                  {itemCount > 0 && (
                    <Tag type="gray" size="sm" {...tagProps}>
                      {itemCount}
                    </Tag>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Rows Container */}
          <div className={`${blockClass}-column__rows`}>{children}</div>
        </div>
      </AddSelectContext.Provider>
    );
  }
);

AddSelectColumn.propTypes = {
  actionsSlot: PropTypes.node,
  allIndeterminate: PropTypes.bool,
  allSelected: PropTypes.bool,
  children: PropTypes.node,
  className: PropTypes.string,
  hideSearch: PropTypes.bool,
  itemCount: PropTypes.number,
  multi: PropTypes.bool,
  /**@ts-ignore */
  onNavigate: PropTypes.func,
  /**@ts-ignore */
  onSearch: PropTypes.func,
  /**@ts-ignore */
  onSelectAll: PropTypes.func,
  searchLabel: PropTypes.string,
  searchPlaceholder: PropTypes.string,
  /**@ts-ignore */
  searchProps: PropTypes.object,
  /**@ts-ignore */
  selectAllCheckboxProps: PropTypes.object,
  showSelectAll: PropTypes.bool,
  /**@ts-ignore */
  tagProps: PropTypes.object,
  title: PropTypes.string,
};

AddSelectColumn.displayName = 'AddSelectColumn';

export default AddSelectColumn;

// packages/ibm-products-web-components/src/components/add-select/add-select-column.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import '@carbon/web-components/es/components/search/index.js';
import '@carbon/web-components/es/components/tag/index.js';
import '@carbon/web-components/es/components/checkbox/index.js';
import { prefix } from '../../globals/settings';
import styles from './add-select-column.scss?lit';

const blockClass = `${prefix}--add-select__next`;

/**
 * Add Select Column component — optional column wrapper providing column-level
 * search, title, and "Select All" functionality. Propagates `multi` context to
 * child rows via the `multi` property/attribute.
 * @element c4p-add-select-column
 * @slot default - AddSelectRow elements
 * @slot actions - Custom actions (filter/sort) placed next to column search
 * @fires c4p-add-select-column-search - Fired when column search changes; detail: { searchTerm }
 * @fires c4p-add-select-column-select-all - Fired when "Select All" checkbox changes; detail: { checked }
 */
@customElement(`${prefix}-add-select-column`)
class CDSAddSelectColumn extends LitElement {
  /**
   * Column title shown in the header
   */
  @property({ type: String })
  title = '';

  /**
   * Label text for the column search input (accessibility)
   */
  @property({ type: String, attribute: 'search-label' })
  searchLabel = 'Search';

  /**
   * Placeholder text for the column search input
   */
  @property({ type: String, attribute: 'search-placeholder' })
  searchPlaceholder = 'Search';

  /**
   * Whether to hide the column search input
   */
  @property({ type: Boolean, attribute: 'hide-search', reflect: true })
  hideSearch = false;

  /**
   * Whether this column uses multi-selection (checkboxes) or single-selection (radio buttons)
   */
  @property({ type: Boolean, reflect: true })
  multi = false;

  /**
   * Whether to show the "Select All" checkbox (only when multi is true)
   */
  @property({ type: Boolean, attribute: 'show-select-all', reflect: true })
  showSelectAll = false;

  /**
   * Total number of items in the column (shown in tag badge)
   */
  @property({ type: Number, attribute: 'item-count' })
  itemCount = 0;

  /**
   * Whether all items are currently selected
   */
  @property({ type: Boolean, attribute: 'all-selected', reflect: true })
  allSelected = false;

  /**
   * Whether the "Select All" checkbox is in an indeterminate state
   */
  @property({ type: Boolean, attribute: 'all-indeterminate', reflect: true })
  allIndeterminate = false;

  /** Internal column search term */
  @state()
  private _searchTerm = '';

  private _handleSearch(event: CustomEvent) {
    this._searchTerm = (event.detail?.value as string) ?? '';
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectColumn).eventSearch,
        {
          bubbles: true,
          cancelable: true,
          composed: true,
          detail: { searchTerm: this._searchTerm },
        }
      )
    );
  }

  private _handleSelectAll(event: CustomEvent) {
    const checked = !!event.detail?.checked;
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectColumn).eventSelectAll,
        {
          bubbles: true,
          cancelable: true,
          composed: true,
          detail: { checked },
        }
      )
    );
  }

  private _handleSlotChange() {
    // Propagate multi to slotted rows
    const slot = this.shadowRoot?.querySelector(
      'slot:not([name])'
    ) as HTMLSlotElement | null;
    if (!slot) {
      return;
    }
    slot.assignedElements({ flatten: true }).forEach((el) => {
      if (el.tagName.toLowerCase() === `${prefix}-add-select-row`) {
        if (this.multi) {
          el.setAttribute('_column-multi', '');
        } else {
          el.removeAttribute('_column-multi');
        }
      }
    });
  }

  updated(changed: Map<string, unknown>) {
    if (changed.has('multi')) {
      this._handleSlotChange();
    }
  }

  render() {
    const {
      title,
      searchLabel,
      searchPlaceholder,
      hideSearch,
      multi,
      showSelectAll,
      itemCount,
      allSelected,
      allIndeterminate,
    } = this;

    const columnClasses = classMap({
      [`${blockClass}-column`]: true,
    });

    const showHeader = showSelectAll || !!title;

    return html`
      <div class=${columnClasses}>
        <!-- Column search with optional actions slot -->
        ${!hideSearch
          ? html`
              <div
                class="${classMap({
                  [`${blockClass}-column__search`]: true,
                  [`${blockClass}-column__search--with-actions`]: true,
                })}"
              >
                <div class="${blockClass}-column__search-input">
                  <cds-search
                    label-text=${searchLabel}
                    placeholder=${searchPlaceholder}
                    size="md"
                    @cds-search-input=${this._handleSearch}
                  ></cds-search>
                </div>
                <slot
                  name="actions"
                  class="${blockClass}-column__actions"
                ></slot>
              </div>
            `
          : nothing}

        <!-- Column header: Select All checkbox or title -->
        ${showHeader
          ? html`
              <div class="${blockClass}-column__header">
                ${showSelectAll && multi
                  ? html`
                      <cds-checkbox
                        class="${blockClass}-column__select-all"
                        ?checked=${allSelected}
                        ?indeterminate=${allIndeterminate}
                        @cds-checkbox-changed=${this._handleSelectAll}
                        label-text="${title}"
                      >
                      </cds-checkbox>
                      ${itemCount > 0
                        ? html`<cds-tag type="gray" size="sm"
                            >${itemCount}</cds-tag
                          >`
                        : nothing}
                    `
                  : html`
                      <div class="${blockClass}-column__title-wrapper">
                        <span class="${blockClass}-column__title"
                          >${title}</span
                        >
                        ${itemCount > 0
                          ? html`<cds-tag type="gray" size="sm"
                              >${itemCount}</cds-tag
                            >`
                          : nothing}
                      </div>
                    `}
              </div>
            `
          : nothing}

        <!-- Rows container -->
        <div class="${blockClass}-column__rows" role="rowgroup">
          <slot @slotchange=${this._handleSlotChange}></slot>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when column search changes.
   * detail: { searchTerm: string }
   */
  static get eventSearch() {
    return `${prefix}-add-select-column-search`;
  }

  /**
   * The name of the custom event fired when "Select All" is toggled.
   * detail: { checked: boolean }
   */
  static get eventSelectAll() {
    return `${prefix}-add-select-column-select-all`;
  }

  static styles = styles;
}

export default CDSAddSelectColumn;
