// packages/ibm-products/src/components/AddSelect/next/AddSelectColumn/AddSelectColumn.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  useState,
  ChangeEvent,
} from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import {
  Search,
  Tag,
  Checkbox,
  Popover,
  PopoverContent,
  IconButton,
} from '@carbon/react';
import { Filter, ArrowsVertical } from '@carbon/react/icons';
import { blockClass, AddSelectContext } from '../context';

/**
 * ----------------
 * AddSelectColumn
 * ----------------
 * A composable column component that wraps AddSelectRow items.
 * Provides optional search, sort, and filter functionality.
 * Lives inside AddSelectList and can have multiple instances.
 */

export interface SortOption {
  id: string;
  label: string;
}

export interface AddSelectColumnProps {
  /**
   * AddSelectRow children
   */
  children?: ReactNode;
  /**
   * Column title displayed in the header
   */
  title?: string;
  /**
   * Whether to show the search input
   */
  showSearch?: boolean;
  /**
   * Placeholder text for the search input
   */
  searchPlaceholder?: string;
  /**
   * Callback when search value changes
   */
  onSearchChange?: (value: string) => void;
  /**
   * Whether to show the sort button
   */
  showSort?: boolean;
  /**
   * Array of sort options
   */
  sortOptions?: SortOption[];
  /**
   * Callback when sort changes
   */
  onSortChange?: (attribute: string, direction: 'asc' | 'desc') => void;
  /**
   * Label for the sort button
   */
  sortLabel?: string;
  /**
   * Whether to show the filter button
   */
  showFilter?: boolean;
  /**
   * Array of filter options
   */
  filterOptions?: string[];
  /**
   * Callback when filters change
   */
  onFilterChange?: (filters: string[]) => void;
  /**
   * Label for the filter button
   */
  filterLabel?: string;
  /**
   * Whether to enable multi-selection (checkboxes) or single selection (radio buttons)
   */
  multi?: boolean;
  /**
   * Whether to show the "Select All" checkbox (only applicable when multi is true)
   */
  showSelectAll?: boolean;
  /**
   * Total number of items in the column (for display in tag)
   */
  itemCount?: number;
  /**
   * Whether all items are currently selected
   */
  allSelected?: boolean;
  /**
   * Callback when "Select All" is toggled
   */
  onSelectAll?: (checked: boolean) => void;
  /**
   * Optional class name
   */
  className?: string;
}

const AddSelectColumn = forwardRef<HTMLDivElement, AddSelectColumnProps>(
  (
    {
      children,
      title = '',
      showSearch = false,
      searchPlaceholder = 'Search',
      onSearchChange,
      showSort = false,
      sortOptions = [],
      onSortChange,
      sortLabel = 'Sort',
      showFilter = false,
      filterOptions = [],
      onFilterChange,
      filterLabel = 'Filter',
      multi = false,
      showSelectAll = false,
      itemCount = 0,
      allSelected = false,
      onSelectAll,
      className,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const [searchTerm, setSearchTerm] = useState('');
    const [filterOpen, setFilterOpen] = useState(false);
    const [selectedFilters, setSelectedFilters] = useState<string[]>([]);
    const [sortAttribute, setSortAttribute] = useState('');
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');

    const handleSearchChange = (e: ChangeEvent<HTMLInputElement>) => {
      const value = e.target.value;
      setSearchTerm(value);
      onSearchChange?.(value);
    };

    const handleFilterChange = (checked: boolean, option: string) => {
      let newFilters: string[];
      if (checked) {
        newFilters = [...selectedFilters, option];
      } else {
        newFilters = selectedFilters.filter((f) => f !== option);
      }
      setSelectedFilters(newFilters);
      onFilterChange?.(newFilters);
    };

    const handleSelectAll = (
      _event: React.ChangeEvent<HTMLInputElement>,
      { checked }: { checked: boolean }
    ) => {
      onSelectAll?.(checked);
    };

    const columnClasses = cx(`${blockClass}-column`, className);

    return (
      <AddSelectContext.Provider value={{ multi }}>
        <div className={columnClasses} ref={ref} {...rest}>
          {/* Search and Controls Section */}
          {(showSearch || showSort || showFilter) && (
            <div className={`${blockClass}-column__search-bar`}>
              <div className={`${blockClass}-column__search-wrapper`}>
                {showSearch && (
                  <Search
                    value={searchTerm}
                    onChange={handleSearchChange}
                    placeholder={searchPlaceholder}
                    className={`${blockClass}-column__search-input`}
                    labelText={searchPlaceholder}
                    size="md"
                  />
                )}
                {(showSort || showFilter) && (
                  <div className={`${blockClass}-column__controls`}>
                    {showSort && sortOptions.length > 0 && (
                      <IconButton
                        label={sortLabel}
                        kind="ghost"
                        size="md"
                        align="bottom"
                        onClick={() => {
                          // Toggle sort direction
                          const newDirection =
                            sortDirection === 'asc' ? 'desc' : 'asc';
                          setSortDirection(newDirection);
                          if (sortOptions[0]) {
                            setSortAttribute(sortOptions[0].id);
                            onSortChange?.(sortOptions[0].id, newDirection);
                          }
                        }}
                        className={`${blockClass}-column__sort-button`}
                      >
                        <ArrowsVertical />
                      </IconButton>
                    )}
                    {showFilter && filterOptions.length > 0 && (
                      <Popover
                        align="bottom-right"
                        open={filterOpen}
                        onRequestClose={() => setFilterOpen(false)}
                      >
                        <IconButton
                          label={filterLabel}
                          kind="ghost"
                          size="md"
                          align="bottom"
                          onClick={() => setFilterOpen(!filterOpen)}
                          className={`${blockClass}-column__filter-button`}
                        >
                          <Filter />
                        </IconButton>
                        <PopoverContent
                          className={`${blockClass}-column__filter-popover`}
                        >
                          {filterOptions.map((option) => (
                            <Checkbox
                              key={option}
                              id={`filter-${option}`}
                              labelText={option}
                              checked={selectedFilters.includes(option)}
                              onChange={(_event, { checked }) =>
                                handleFilterChange(checked, option)
                              }
                            />
                          ))}
                        </PopoverContent>
                      </Popover>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Header with Select All */}
          {(showSelectAll || title) && (
            <div className={`${blockClass}-column__header`}>
              {showSelectAll && multi ? (
                <Checkbox
                  id={`select-all-${title}`}
                  className={`${blockClass}-column__select-all`}
                  checked={allSelected}
                  onChange={handleSelectAll}
                  labelText={
                    <>
                      <span className={`${blockClass}-column__title`}>
                        {title}
                      </span>
                      {itemCount > 0 && (
                        <Tag type="gray" size="sm">
                          {itemCount}
                        </Tag>
                      )}
                    </>
                  }
                />
              ) : (
                <div className={`${blockClass}-column__title-wrapper`}>
                  <span className={`${blockClass}-column__title`}>{title}</span>
                  {itemCount > 0 && (
                    <Tag type="gray" size="sm">
                      {itemCount}
                    </Tag>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Rows Container */}
          <div className={`${blockClass}-column__rows`}>{children}</div>
        </div>
      </AddSelectContext.Provider>
    );
  }
);

AddSelectColumn.propTypes = {
  allSelected: PropTypes.bool,
  children: PropTypes.node,
  className: PropTypes.string,
  filterLabel: PropTypes.string,
  filterOptions: PropTypes.arrayOf(PropTypes.string),
  itemCount: PropTypes.number,
  multi: PropTypes.bool,
  /**@ts-ignore */
  onFilterChange: PropTypes.func,
  /**@ts-ignore */
  onSearchChange: PropTypes.func,
  /**@ts-ignore */
  onSelectAll: PropTypes.func,
  /**@ts-ignore */
  onSortChange: PropTypes.func,
  searchPlaceholder: PropTypes.string,
  showFilter: PropTypes.bool,
  showSearch: PropTypes.bool,
  showSelectAll: PropTypes.bool,
  showSort: PropTypes.bool,
  sortLabel: PropTypes.string,
  sortOptions: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      label: PropTypes.string.isRequired,
    })
  ),
  title: PropTypes.string,
};

AddSelectColumn.displayName = 'AddSelectColumn';

export default AddSelectColumn;

// packages/ibm-products-web-components/src/components/add-select/add-select-column.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import '@carbon/web-components/es/components/search/index.js';
import '@carbon/web-components/es/components/tag/index.js';
import '@carbon/web-components/es/components/checkbox/index.js';
import { prefix } from '../../globals/settings';
import styles from './add-select-column.scss?lit';

const blockClass = `${prefix}--add-select__next`;

/**
 * Add Select Column component — optional column wrapper providing column-level
 * search, title, and "Select All" functionality. Propagates `multi` context to
 * child rows via the `multi` property/attribute.
 * @element c4p-add-select-column
 * @slot default - AddSelectRow elements
 * @slot actions - Custom actions (filter/sort) placed next to column search
 * @fires c4p-add-select-column-search - Fired when column search changes; detail: { searchTerm }
 * @fires c4p-add-select-column-select-all - Fired when "Select All" checkbox changes; detail: { checked }
 */
@customElement(`${prefix}-add-select-column`)
class CDSAddSelectColumn extends LitElement {
  /**
   * Column title shown in the header
   */
  @property({ type: String })
  title = '';

  /**
   * Label text for the column search input (accessibility)
   */
  @property({ type: String, attribute: 'search-label' })
  searchLabel = 'Search';

  /**
   * Placeholder text for the column search input
   */
  @property({ type: String, attribute: 'search-placeholder' })
  searchPlaceholder = 'Search';

  /**
   * Whether to hide the column search input
   */
  @property({ type: Boolean, attribute: 'hide-search', reflect: true })
  hideSearch = false;

  /**
   * Whether this column uses multi-selection (checkboxes) or single-selection (radio buttons)
   */
  @property({ type: Boolean, reflect: true })
  multi = false;

  /**
   * Whether to show the "Select All" checkbox (only when multi is true)
   */
  @property({ type: Boolean, attribute: 'show-select-all', reflect: true })
  showSelectAll = false;

  /**
   * Total number of items in the column (shown in tag badge)
   */
  @property({ type: Number, attribute: 'item-count' })
  itemCount = 0;

  /**
   * Whether all items are currently selected
   */
  @property({ type: Boolean, attribute: 'all-selected', reflect: true })
  allSelected = false;

  /**
   * Whether the "Select All" checkbox is in an indeterminate state
   */
  @property({ type: Boolean, attribute: 'all-indeterminate', reflect: true })
  allIndeterminate = false;

  /** Internal column search term */
  @state()
  private _searchTerm = '';

  /** Whether the actions slot has any assigned content */
  @state()
  private _hasActionsSlot = false;

  private _handleActionsSlotChange(e: Event) {
    const slot = e.target as HTMLSlotElement;
    this._hasActionsSlot = slot.assignedElements({ flatten: true }).length > 0;
  }

  private _handleSearch(event: CustomEvent) {
    this._searchTerm = (event.detail?.value as string) ?? '';
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectColumn).eventSearch,
        {
          bubbles: true,
          cancelable: true,
          composed: true,
          detail: { searchTerm: this._searchTerm },
        }
      )
    );
  }

  private _handleSelectAll(event: CustomEvent) {
    const checked = !!event.detail?.checked;
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectColumn).eventSelectAll,
        {
          bubbles: true,
          cancelable: true,
          composed: true,
          detail: { checked },
        }
      )
    );
  }

  private _handleSlotChange() {
    // Propagate multi to slotted rows
    const slot = this.shadowRoot?.querySelector(
      'slot:not([name])'
    ) as HTMLSlotElement | null;
    if (!slot) {
      return;
    }
    slot.assignedElements({ flatten: true }).forEach((el) => {
      if (el.tagName.toLowerCase() === `${prefix}-add-select-row`) {
        if (this.multi) {
          el.setAttribute('_column-multi', '');
        } else {
          el.removeAttribute('_column-multi');
        }
      }
    });
  }

  updated(changed: Map<string, unknown>) {
    if (changed.has('multi')) {
      this._handleSlotChange();
    }
  }

  render() {
    const {
      title,
      searchLabel,
      searchPlaceholder,
      hideSearch,
      multi,
      showSelectAll,
      itemCount,
      allSelected,
      allIndeterminate,
    } = this;

    const columnClasses = classMap({
      [`${blockClass}-column`]: true,
    });

    const showHeader = showSelectAll || !!title;

    return html`
      <div class=${columnClasses}>
        <!-- Column search with optional actions slot -->
        ${!hideSearch
          ? html`
              <div
                class="${classMap({
                  [`${blockClass}-column__search`]: true,
                  [`${blockClass}-column__search--with-actions`]:
                    this._hasActionsSlot,
                })}"
              >
                <div
                  class="${this._hasActionsSlot
                    ? `${blockClass}-column__search-input`
                    : ''}"
                >
                  <cds-search
                    label-text=${searchLabel}
                    placeholder=${searchPlaceholder}
                    size="md"
                    @cds-search-input=${this._handleSearch}
                  ></cds-search>
                </div>
                <slot
                  name="actions"
                  class="${blockClass}-column__actions"
                  @slotchange=${this._handleActionsSlotChange}
                ></slot>
              </div>
            `
          : nothing}

        <!-- Column header: Select All checkbox or title -->
        ${showHeader
          ? html`
              <div class="${blockClass}-column__header">
                ${showSelectAll && multi
                  ? html`
                      <div class="${blockClass}-column__title-wrapper">
                        <cds-checkbox
                          class="${blockClass}-column__select-all"
                          ?checked=${allSelected}
                          ?indeterminate=${allIndeterminate}
                          @cds-checkbox-changed=${this._handleSelectAll}
                          label-text="${title}"
                        ></cds-checkbox>
                        ${itemCount > 0
                          ? html`<cds-tag type="gray" size="sm"
                              >${itemCount}</cds-tag
                            >`
                          : nothing}
                      </div>
                    `
                  : html`
                      <div class="${blockClass}-column__title-wrapper">
                        <span class="${blockClass}-column__title"
                          >${title}</span
                        >
                        ${itemCount > 0
                          ? html`<cds-tag type="gray" size="sm"
                              >${itemCount}</cds-tag
                            >`
                          : nothing}
                      </div>
                    `}
              </div>
            `
          : nothing}

        <!-- Rows container -->
        <div class="${blockClass}-column__rows" role="rowgroup">
          <slot @slotchange=${this._handleSlotChange}></slot>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when column search changes.
   * detail: { searchTerm: string }
   */
  static get eventSearch() {
    return `${prefix}-add-select-column-search`;
  }

  /**
   * The name of the custom event fired when "Select All" is toggled.
   * detail: { checked: boolean }
   */
  static get eventSelectAll() {
    return `${prefix}-add-select-column-select-all`;
  }

  static styles = styles;
}

export default CDSAddSelectColumn;
