// packages/ibm-products-web-components/src/components/full-page-error/full-page-error.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, LitElement } from 'lit';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import { prefix, carbonPrefix } from '../../globals/settings';

import { error403SVG } from './assets/error403SVG';
import { error404SVG } from './assets/error404SVG';
import { errorGenericSVG } from './assets/errorGenericSVG';
import { Kind } from './types';

import styles from './full-page-error.scss?lit';

const componentName = 'full-page-error';
export const blockClass = `${prefix}--${componentName}`;
const elementName = `${prefix}-${componentName}`; // c4p-full-page-error

/**
 * FullPageError.
 *
 * @element c4p-full-page-error
 * @csspart dialog The dialog.
 */
@customElement(elementName)
class CDSFullPageError extends LitElement {
  static styles = styles;
  static errorData = {
    [Kind.Error403]: {
      svg: error403SVG,
    },
    [Kind.Error404]: {
      svg: error404SVG,
    },
    [Kind.Custom]: {
      svg: errorGenericSVG,
    },
  };

  @property({ type: String, reflect: true })
  label: string = 'Label';

  @property({ type: String, reflect: true })
  description: string = 'Description goes here, this is the default';

  @property({ type: String, reflect: true })
  kind: Kind = Kind.Custom;

  @property({ type: String, reflect: true })
  title: string = 'Title';

  render() {
    return html` <div class=${this.classList} role="main">
      <div class=${`${blockClass}__container`}>
        <div class=${`${carbonPrefix}--css-grid ${blockClass}__grid`}>
          <div
            class=${`${blockClass}__column ${carbonPrefix}--css-grid-column ${carbonPrefix}--sm:col-span-4 ${carbonPrefix}--md:col-span-3 ${carbonPrefix}--lg:col-span-6`}
          >
            <h1 class=${`${blockClass}__title`}>
              <span class=${`${blockClass}__label`}>
                <span aria-hidden="true">↳ </span>
                ${this.label}
              </span>
              <span>${this.title}</span>
            </h1>
            <p class=${`${blockClass}__description`}>${this.description}</p>
            <div class=${`${blockClass}__body`}><slot></slot></div>
          </div>
          <div
            class=${`${carbonPrefix}--css-grid-column ${carbonPrefix}--sm:col-span-4 ${carbonPrefix}--md:col-span-5 ${carbonPrefix}--lg:col-span-10`}
          >
            <div class=${`${blockClass}__svg-container`}>
              ${CDSFullPageError.errorData[this.kind].svg}
            </div>
          </div>
        </div>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    [elementName]: CDSFullPageError;
  }
}

export default CDSFullPageError;

// packages/ibm-products/src/components/FullPageError/FullPageError.tsx
/**
 * Copyright IBM Corp. 2024, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Carbon and package components we use.
import { Column, Grid } from '@carbon/react';
// Import portions of React that are needed.
import React, { ReactNode } from 'react';

import { Error403SVG } from './assets/Error403SVG';
import { Error404SVG } from './assets/Error404SVG';
import { ErrorGenericSVG } from './assets/ErrorGenericSVG';
// Other standard imports.
import PropTypes from 'prop-types';
import cx from 'classnames';
import { getDevtoolsProps } from '../../global/js/utils/devtools';
import { pkg } from '../../settings';

// The block part of our conventional BEM class names (blockClass__E--M).
const blockClass = `${pkg.prefix}--full-page-error`;
const componentName = 'FullPageError';

export interface FullPageErrorProps {
  /**
   * Provide the contents of the FullPageError.
   */
  children?: ReactNode;
  /**
   * Provide an optional class to be applied to the containing node.
   */
  className?: string;
  /**
   * String that will provide the description for the error code. <br/>
   * This is optional for 403 and 404 kinds, and passing this would override their default descriptions.
   */
  description: string;

  /**
   * The kind of error page to be displayed, default is custom
   */
  kind?: 'custom' | '403' | '404';

  /**
   * String that will describe the error that occurred
   */
  label: string;

  /**
   * This will be for the main title of the FullPageError component
   */
  title: string;
}

// Default values for props
const defaults = {
  kind: 'custom',
};

/**
 * Display a full-page error when the requested page is unavailable to the user.
 * This is typically caused by issues with the requested URL or access permissions.
 */
export const FullPageError = React.forwardRef<HTMLDivElement, FullPageErrorProps>(
  (
    {
      // The component props, in alphabetical order (for consistency).
      children,
      className,
      description,
      label,
      kind = defaults.kind,
      title,

      // Collect any other property values passed in.
      ...rest
    },
    ref
  ) => {
    const errorData = {
      403: {
        svg: (
          <Error403SVG className={`${blockClass}__svg ${blockClass}__403`} />
        ),
      },
      404: {
        svg: (
          <Error404SVG className={`${blockClass}__svg ${blockClass}__404`} />
        ),
      },
      custom: {
        svg: (
          <ErrorGenericSVG
            className={`${blockClass}__svg ${blockClass}__custom`}
          />
        ),
      },
    };
    return (
      <div
        {...rest}
        className={cx(blockClass, className)}
        ref={ref}
        role="main"
        {...getDevtoolsProps(componentName)}
      >
        <div className={`${blockClass}__container`}>
          <Grid className={`${blockClass}__grid`}>
            <Column sm={4} md={3} lg={6} className={`${blockClass}__column`}>
              <h1 className={`${blockClass}__title`}>
                <span className={`${blockClass}__label`}>
                  <span aria-hidden="true">↳ </span>
                  {label}
                </span>
                <span>{title}</span>
              </h1>
              <p className={`${blockClass}__description`}>{description}</p>
              <div className={`${blockClass}__body`}>{children}</div>
            </Column>
            <Column sm={4} md={5} lg={10}>
              <div className={`${blockClass}__svg-container`}>
                {errorData[kind].svg}
              </div>
            </Column>
          </Grid>
        </div>
      </div>
    );
  }
);

// Return a placeholder if not released and not enabled by feature flag

// The display name of the component, used by React. Note that displayName
// is used in preference to relying on function.name.
FullPageError.displayName = componentName;

// The types and DocGen commentary for the component props,
// in alphabetical order (for consistency).
// See https://www.npmjs.com/package/prop-types#usage.
FullPageError.propTypes = {
  /**
   * Provide the contents of the FullPageError.
   */
  children: PropTypes.node,

  /**
   * Provide an optional class to be applied to the containing node.
   */
  className: PropTypes.string,
  /**
   * String that will provide the description for the error code. <br/>
   * This is optional for 403 and 404 kinds, and passing this would override their default descriptions.
   */
  description: PropTypes.string.isRequired,

  /**
   * The kind of error page to be displayed, default is custom
   */
  kind: PropTypes.oneOf(['custom', '403', '404']),

  /**
   * String that will describe the error that occurred
   */
  label: PropTypes.string.isRequired,

  /**
   * This will be for the main title of the FullPageError component
   */
  title: PropTypes.string.isRequired,
};
