// packages/ibm-products-web-components/src/components/add-select/add-select-row/add-select-row.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import '@carbon/web-components/es/components/checkbox/index.js';
import '@carbon/web-components/es/components/radio-button/index.js';
import { iconLoader } from '@carbon/web-components/es/globals/internal/icon-loader.js';
import ChevronRight16 from '@carbon/icons/es/chevron--right/16';

import { prefix } from '../../../globals/settings';
import styles from './add-select-row.scss?lit';

const blockClass = `${prefix}--add-select__next-row`;

/**
 * Add Select Row component - represents a single selectable row
 * @element c4p-add-select-row
 * @slot default - The main content of the row (title, subtitle, etc.)
 * @slot icon - Optional icon slot
 * @slot meta - Optional metadata slot
 * @fires c4p-add-select-row-select - Fired when row is selected/deselected
 * @fires c4p-add-select-row-navigate - Fired when navigating to children
 */
@customElement(`${prefix}-add-select-row`)
class CDSAddSelectRow extends LitElement {
  /**
   * Whether this is part of a multi-select list (inherited from parent c4p-add-select)
   * @private
   */
  private get _multi(): boolean {
    const parent = this.closest(`${prefix}-add-select`) as any;
    return parent?.multi ?? false;
  }
  /**
   * Unique identifier for the item
   */
  @property({ type: String, attribute: 'item-id' })
  itemId = '';

  /**
   * Item title
   */
  @property({ type: String })
  title = '';

  /**
   * Item subtitle
   */
  @property({ type: String })
  subtitle = '';

  /**
   * Item value
   */
  @property({ type: String })
  value = '';

  /**
   * Whether the item is selected
   */
  @property({ type: Boolean, reflect: true })
  selected = false;

  /**
   * Whether the item is disabled
   */
  @property({ type: Boolean })
  disabled = false;

  /**
   * Whether the item has children (for navigation)
   */
  @property({ type: Boolean, attribute: 'has-children' })
  hasChildren = false;

  /**
   * Parent ID for hierarchical navigation
   */
  @property({ type: String, attribute: 'parent-id' })
  parentId = '';

  /**
   * Handle navigation to children
   */
  private _handleNavigate(event: Event) {
    event.stopPropagation();

    if (!this.hasChildren) {
      return;
    }

    // Emit navigation event
    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: {
        itemId: this.itemId,
        title: this.title,
        parentId: this.parentId,
      },
    };
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectRow).eventNavigate,
        init
      )
    );
  }

  /**
   * Handle selection change from checkbox/radio button
   */
  private _handleSelect(event: Event) {
    if (this.disabled) {
      event.preventDefault();
      return;
    }

    // Get the new checked state from the event
    const target = event.target as any;
    this.selected = target.checked || false;

    // Emit selection event
    this._emitSelectionEvent();
  }

  /**
   * Emit selection event
   */
  private _emitSelectionEvent() {
    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: {
        itemId: this.itemId,
        selected: this.selected,
        value: this.value,
      },
    };
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectRow).eventSelect,
        init
      )
    );
  }

  render() {
    const {
      itemId,
      title,
      subtitle,
      selected,
      disabled,
      hasChildren,
      _handleSelect: handleSelect,
    } = this;

    const rowClasses = classMap({
      [`${blockClass}-row`]: true,
      [`${blockClass}-row--selected`]: selected,
      [`${blockClass}-row--disabled`]: disabled,
    });

    return html`
      <div
        class=${rowClasses}
        role="row"
        aria-selected=${selected}
        tabindex="-1"
        ?data-has-children=${hasChildren}
      >
        <div class="${blockClass}-row__cell" role="gridcell">
          <div class="${blockClass}-row__cell-wrapper">
            ${this._multi
              ? html`
                  <cds-checkbox
                    ?checked=${selected}
                    ?disabled=${disabled}
                    @cds-checkbox-changed=${handleSelect}
                    label-text=${title}
                    tabindex="-1"
                  >
                  </cds-checkbox>
                `
              : html`
                  <cds-radio-button
                    ?checked=${selected}
                    ?disabled=${disabled}
                    @cds-radio-button-changed=${handleSelect}
                    label-text=${title}
                    value=${itemId}
                    tabindex="-1"
                  >
                  </cds-radio-button>
                `}

            <div class="${blockClass}-row__content">
              <slot name="icon"></slot>
              <div class="${blockClass}-row__text">
                <div class="${blockClass}-row__title">${title}</div>
                ${subtitle &&
                html`<div class="${blockClass}-row__subtitle">
                  ${subtitle}
                </div>`}
              </div>
              <slot name="meta"></slot>
            </div>

            ${hasChildren
              ? html`
                  <div
                    class="${blockClass}-row__nav-indicator"
                    @click=${this._handleNavigate}
                    role="button"
                    tabindex="-1"
                    aria-label="Navigate to children"
                  >
                    <slot name="nav-icon">
                      ${iconLoader(ChevronRight16, {
                        slot: 'icon',
                      })}
                    </slot>
                  </div>
                `
              : nothing}
          </div>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when row is selected/deselected
   */
  static get eventSelect() {
    return `${prefix}-add-select-row-select`;
  }

  /**
   * The name of the custom event fired when navigating to children
   */
  static get eventNavigate() {
    return `${prefix}-add-select-row-navigate`;
  }

  static styles = styles;
}

export default CDSAddSelectRow;

// packages/ibm-products/src/components/AddSelect/next/AddSelectRow/AddSelectRow.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  useContext,
  MouseEvent,
} from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { Checkbox, RadioButton } from '@carbon/react';
import { ChevronRight } from '@carbon/react/icons';
import { blockClass, AddSelectContext } from '../context';

/**
 * ----------------
 * AddSelectRow
 * ----------------
 */

export interface AddSelectRowProps {
  /**
   * Unique identifier for the item
   */
  itemId: string;
  /**
   * Item title
   */
  title: string;
  /**
   * Item subtitle
   */
  subtitle?: string;
  /**
   * Item value
   */
  value: string;
  /**
   * Whether the item is selected
   */
  selected?: boolean;
  /**
   * Whether the item is disabled
   */
  disabled?: boolean;
  /**
   * Whether the item has children (for navigation)
   */
  hasChildren?: boolean;
  /**
   * Parent ID for hierarchical navigation
   */
  parentId?: string;
  /**
   * Optional icon slot
   */
  icon?: ReactNode;
  /**
   * Optional metadata slot
   */
  meta?: ReactNode;
  /**
   * Optional class name
   */
  className?: string;
}

const AddSelectRow = forwardRef<HTMLDivElement, AddSelectRowProps>(
  (
    {
      itemId,
      title,
      subtitle,
      value,
      selected = false,
      disabled = false,
      hasChildren = false,
      parentId = '',
      icon,
      meta,
      className,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const { multi, onItemSelect, onNavigate, selectedItems } =
      useContext(AddSelectContext);

    // Use context's selected state if available
    const isSelected = selectedItems?.has(itemId) ?? selected;

    const handleSelect = () => {
      if (disabled) {
        return;
      }
      const newSelected = !isSelected;
      onItemSelect?.(itemId, newSelected, value);
    };

    const handleNavigate = (event: MouseEvent<HTMLDivElement>) => {
      event.stopPropagation();
      if (!hasChildren) {
        return;
      }
      onNavigate?.(itemId, title, parentId);
    };

    const rowClasses = cx(`${blockClass}-row`, className, {
      [`${blockClass}-row--selected`]: isSelected,
      [`${blockClass}-row--disabled`]: disabled,
    });

    return (
      <div
        className={rowClasses}
        role="row"
        aria-selected={isSelected}
        tabIndex={-1}
        data-has-children={hasChildren || undefined}
        ref={ref}
        {...rest}
      >
        <div className={`${blockClass}-row__cell`} role="gridcell">
          <div className={`${blockClass}-row__cell-wrapper`}>
            {multi ? (
              <Checkbox
                id={`checkbox-${itemId}`}
                checked={isSelected}
                disabled={disabled}
                labelText={title}
                onChange={handleSelect}
                tabIndex={-1}
              />
            ) : (
              <RadioButton
                id={`radio-${itemId}`}
                checked={isSelected}
                disabled={disabled}
                labelText={title}
                value={itemId}
                onChange={handleSelect}
                tabIndex={-1}
              />
            )}

            <div className={`${blockClass}-row__content`}>
              {icon && <div className={`${blockClass}-row__icon`}>{icon}</div>}
              <div className={`${blockClass}-row__text`}>
                <div className={`${blockClass}-row__title`}>{title}</div>
                {subtitle && (
                  <div className={`${blockClass}-row__subtitle`}>
                    {subtitle}
                  </div>
                )}
              </div>
              {meta && <div className={`${blockClass}-row__meta`}>{meta}</div>}
            </div>

            {hasChildren && (
              <div
                className={`${blockClass}-row__nav-indicator`}
                onClick={handleNavigate}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    e.stopPropagation();
                    if (hasChildren) {
                      onNavigate?.(itemId, title, parentId);
                    }
                  }
                }}
                role="button"
                tabIndex={-1}
                aria-label="Navigate to children"
              >
                <ChevronRight size={16} />
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }
);

AddSelectRow.propTypes = {
  className: PropTypes.string,
  disabled: PropTypes.bool,
  hasChildren: PropTypes.bool,
  icon: PropTypes.node,
  itemId: PropTypes.string.isRequired,
  meta: PropTypes.node,
  parentId: PropTypes.string,
  selected: PropTypes.bool,
  subtitle: PropTypes.string,
  title: PropTypes.string.isRequired,
  value: PropTypes.string.isRequired,
};

AddSelectRow.displayName = 'AddSelectRow';

export default AddSelectRow;
