// packages/ibm-products-web-components/src/components/step-flow/_story-assets/step-tearsheet.ts
/**
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, PropertyValues, html, nothing } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { SignalWatcher } from '@lit-labs/signals';
import styles from '../story-styles.scss?lit';
import { StepInstance } from '../step-flow-signal';
import '@carbon/web-components/es/components/progress-indicator/index.js';
import '@carbon/web-components/es/components/stack/index.js';
import '@carbon/web-components/es/components/code-snippet/index.js';
import '../step-group';
import '../../tearsheet/index.js';
import {
  registerFocusableContainers,
  trapFocus,
} from '../../../utilities/manageFocusTrap/manageFocusTrap';

interface FormStateType {
  email?: string;
  city?: string;
  state?: string;
}

@customElement('step-tearsheet')
export class StepTearsheet extends SignalWatcher(LitElement) {
  @state()
  private _open: boolean = false;

  @state()
  private _email: string = '';

  @state()
  private _city: string = '';

  @state()
  private _state: string = '';

  private _trapFocusAPI: { cleanup: () => void } | null = null;

  private _onButtonClick() {
    this._open = true;
  }

  private _handleCancelButton() {
    this._open = false;
    this._stepInfo.reset();
  }

  private _handleBackButton() {
    const { currentStep } = this._stepInfo.data;
    if (currentStep === 0) {
      return;
    }
    return this._stepInfo.handlePrevious();
  }

  private _handleNextButton() {
    const { currentStep, totalSteps } = this._stepInfo.data;
    if (currentStep + 1 === totalSteps) {
      this._open = false;
      this._stepInfo.reset();
      return;
    }
    return this._stepInfo.handleNext();
  }

  private _handleEmailInput(e) {
    const savedFormState = structuredClone(
      this._stepInfo.data.formState
    ) as FormStateType;
    savedFormState.email = e.target.value;
    this._stepInfo.updateFormState = savedFormState;
  }

  private _handleCityInput(e) {
    const savedFormState = structuredClone(
      this._stepInfo.data.formState
    ) as FormStateType;
    savedFormState.city = e.target.value;
    this._stepInfo.updateFormState = savedFormState;
  }

  private _handleStateInput(e) {
    const savedFormState = structuredClone(
      this._stepInfo.data.formState
    ) as FormStateType;
    savedFormState.state = e.target.value;
    this._stepInfo.updateFormState = savedFormState;
  }

  private _stepInfo = new StepInstance();

  connectedCallback(): void {
    super.connectedCallback();
    this._stepInfo.updateTotalStepCount = 3;
  }

  disconnectedCallback(): void {
    this._trapFocusAPI?.cleanup();
  }

  protected firstUpdated(_changedProperties: PropertyValues): void {
    registerFocusableContainers(
      this.shadowRoot?.querySelector(`c4p-tearsheet`)
    );
  }

  updated(changedProps: Map<string | number | symbol, unknown>) {
    if (changedProps.has('_open')) {
      const isOpen = this._open;
      if (isOpen) {
        // `focusableContainers` holds the containers where we can query DOM elements.
        // Our strategy here is to let child/slotted components register their containers,
        // which are then passed to `trapFocus`. This allows the utility to query elements
        // directly without being blocked by shadow DOM boundaries.

        this._trapFocusAPI = trapFocus();
      }
    }
  }

  render() {
    const { formState, totalSteps, currentStep } = this._stepInfo.data;

    return html` <cds-button
        type="button"
        size="md"
        @click="${this._onButtonClick}"
      >
        Start create flow
      </cds-button>
      <c4p-tearsheet
        class=${'step-tearsheet-with-util'}
        selector-initial-focus=${'#tearsheet-story-text-input-a'}
        ?open=${this._open}
        width=${'wide'}
        influencer-placement=${'left'}
        prevent-close-on-click-outside
      >
        <!-- default slotted content -->
        <step-group>
          ${currentStep + 1 === 1
            ? html`<div>
                <cds-stack gap="6" orientation="horizontal">
                  <cds-text-input
                    label="Email"
                    id="tearsheet-story-text-input-a"
                    value=${this._email}
                    @input="${this._handleEmailInput}"
                  ></cds-text-input>
                </cds-stack>
              </div>`
            : nothing}
          ${currentStep + 1 === 2
            ? html`<div>
                <cds-stack gap="6" orientation="horizontal">
                  <cds-text-input
                    label="City"
                    id="tearsheet-story-text-input-city"
                    value=${this._city}
                    @input="${this._handleCityInput}"
                  ></cds-text-input>
                  <cds-text-input
                    label="State"
                    id="tearsheet-story-text-input-state"
                    value=${this._state}
                    @input="${this._handleStateInput}"
                  ></cds-text-input>
                </cds-stack>
              </div>`
            : nothing}
          ${currentStep + 1 === 3
            ? html`<div>
                <!-- //cspell: disable -->
                <cds-code-snippet
                  type="multi"
                  copy-text=""
                  maxcollapsednumberofrows="15"
                  maxexpandednumberofrows=""
                  mincollapsednumberofrows="3"
                  minexpandednumberofrows=""
                  show-less-text="Show less"
                  show-more-text="Show more"
                  feedback=""
                  feedback-timeout="0"
                  tooltip-content="Copy to clipboard"
                >
                  ${JSON.stringify(formState, null, 2)}
                </cds-code-snippet>
                <!-- //cspell: enable -->
              </div>`
            : nothing}
        </step-group>

        <!-- slotted header label -->
        <span slot="label">Optional label for context</span>

        <!-- slotted header title -->
        <span slot="title">Create tearsheet title</span>

        <!-- slotted header description -->
        <span slot="description">
          This is a description for the tearsheet, providing an opportunity to
          describe the flow over a couple of lines in the header of the
          tearsheet.
        </span>

        <!-- slotted action items cds-buttons -->
        <cds-button
          slot="actions"
          kind=${'ghost'}
          @click=${this._handleCancelButton}
        >
          Cancel
        </cds-button>
        <cds-button
          slot="actions"
          kind=${'secondary'}
          @click=${this._handleBackButton}
        >
          Back
        </cds-button>
        <cds-button slot="actions" @click=${this._handleNextButton}>
          ${currentStep + 1 < totalSteps ? 'Next' : 'Submit'}
        </cds-button>
        <!-- slotted influencer -->
        <div slot="influencer">
          <cds-progress-indicator
            vertical
            class=${`custom-step-util__dummy-content-block`}
          >
            <cds-progress-step
              label="First step"
              state=${currentStep + 1 === 1 ? 'current' : 'complete'}
            ></cds-progress-step>
            <cds-progress-step
              label="Second step"
              state=${currentStep + 1 === 2
                ? 'current'
                : currentStep + 1 < 2
                  ? 'incomplete'
                  : 'complete'}
            ></cds-progress-step>
            <cds-progress-step
              label="Third step"
              state=${currentStep + 1 === 3
                ? 'current'
                : currentStep + 1 < 3
                  ? 'incomplete'
                  : 'complete'}
            ></cds-progress-step>
          </cds-progress-indicator>
        </div>
      </c4p-tearsheet>`;
  }
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

declare global {
  interface HTMLElementTagNameMap {
    'step-tearsheet': StepTearsheet;
  }
}

// packages/ibm-products/src/components/Tearsheet/next/_story-assets/StepTearsheet.tsx
/**
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { ReactNode, RefObject, useEffect } from 'react';
import {
  StepGroup,
  StepContextType,
  useStepContext,
} from '@carbon/utilities-react';
import { Tearsheet } from '../Tearsheet';
import {
  Button,
  CodeSnippet,
  Heading,
  ProgressIndicator,
  ProgressStep,
  Section,
  TextInput,
} from '@carbon/react';

interface Props {
  children?: ReactNode;
  influencer?: ((a: StepContextType) => ReactNode) | null;
  open?: boolean;
  onClose?: () => void;
  title?: ReactNode;
  hasCloseIcon?: boolean;
  closeIconDescription?: string;
  selectorPrimaryFocus?: string;
  setOpen?: (open: boolean) => void;
  progressIndicator?: 'vertical' | 'horizontal';
  launcherButtonRef?: RefObject<HTMLButtonElement | null>;
}

export const TearsheetWithSteps = ({
  children,
  open,
  setOpen,
  onClose,
  influencer,
  title,
  hasCloseIcon,
  closeIconDescription = 'Close',
  selectorPrimaryFocus,
  progressIndicator = 'vertical',
  launcherButtonRef,
  ...rest
}: Props) => {
  const {
    totalSteps,
    currentStep,
    handleNext,
    handlePrevious,
    handleGoToStep,
  } = useStepContext();

  return (
    <Tearsheet
      open={open}
      variant={'wide'}
      onClose={() => setOpen?.(false)}
      launcherButtonRef={launcherButtonRef}
    >
      <Tearsheet.Header>
        <Tearsheet.HeaderContent
          label="Customer data"
          title="Title of the tearsheet "
          description="This is a description for the tearsheet, providing an opportunity to describe the flow over a couple of lines in the header of the tearsheet."
          headerActions={
            <Tearsheet.HeaderActions
              menuButtonProps={{ label: 'Actions', kind: 'tertiary' }}
            >
              <Tearsheet.HeaderActionItem overflowItemLabel="Action 1">
                <Button kind="tertiary" size="sm">
                  Action 1
                </Button>
              </Tearsheet.HeaderActionItem>
              <Tearsheet.HeaderActionItem overflowItemLabel="Action 2">
                <Button kind="tertiary" size="sm">
                  Action 2
                </Button>
              </Tearsheet.HeaderActionItem>
              <Tearsheet.HeaderActionItem overflowItemLabel="Action 3">
                <Button kind="tertiary" size="sm">
                  Action 3
                </Button>
              </Tearsheet.HeaderActionItem>
            </Tearsheet.HeaderActions>
          }
        ></Tearsheet.HeaderContent>
        {progressIndicator !== 'vertical' && (
          <ProgressIndicator>
            <ProgressStep
              complete={currentStep > 1}
              current={currentStep === 1}
              label="Step 1"
              secondaryLabel="Optional label"
            />
            <ProgressStep
              complete={currentStep > 2}
              current={currentStep === 2}
              label="Step 2"
            />
            <ProgressStep
              current={currentStep === 3}
              label="Step 3"
              complete={currentStep > 3}
            />
          </ProgressIndicator>
        )}
      </Tearsheet.Header>
      {progressIndicator === 'vertical' && (
        <Tearsheet.Influencer>
          <ProgressIndicator vertical>
            <ProgressStep
              complete={currentStep > 1}
              current={currentStep === 1}
              label="Step 1"
              secondaryLabel="Optional label"
            />
            <ProgressStep
              complete={currentStep > 2}
              current={currentStep === 2}
              label="Step 2"
            />
            <ProgressStep
              current={currentStep === 3}
              label="Step 3"
              complete={currentStep > 3}
            />
          </ProgressIndicator>
        </Tearsheet.Influencer>
      )}
      <Tearsheet.Body>
        <Tearsheet.MainContent>
          <StepGroup>
            <Step1 />
            <Step2 />
            <Step3 />
            {/* {introExample && selectedFlow === 'plus' && <PlusOnly />} */}
          </StepGroup>
        </Tearsheet.MainContent>
      </Tearsheet.Body>
      <Tearsheet.Footer>
        <div className="default__action-buttons">
          <Button
            className="step-action-button step-action-button__cancel"
            kind="ghost"
            onClick={() => {
              setOpen?.(false);
            }}
            size="xl"
          >
            Cancel
          </Button>
          <Button
            className="step-action-button"
            kind="secondary"
            onClick={() => {
              handlePrevious();
            }}
            disabled={currentStep === 1}
            size="xl"
          >
            Back
          </Button>
          <Button
            size="xl"
            className="step-action-button"
            onClick={() => {
              if (currentStep === totalSteps) {
                // submit
                setOpen?.(false);
                handleGoToStep(1);
              } else {
                handleNext();
              }
            }}
          >
            {currentStep === totalSteps ? 'Submit' : 'Next'}
          </Button>
        </div>
      </Tearsheet.Footer>
    </Tearsheet>
  );
};
const useStepFocus = (stepPrimaryFocus: string) => {
  useEffect(() => {
    const stepFocusElement = document?.querySelector(
      stepPrimaryFocus
    ) as HTMLElement;
    stepFocusElement?.focus();
  }, [stepPrimaryFocus]);
};
function Step1() {
  const { setFormState, formState } = useStepContext();
  const { email } = formState ?? {};
  useStepFocus('#email');
  return (
    <Section className="step-container">
      <Heading className="step-heading">Step 1</Heading>
      <TextInput
        id="email"
        onChange={(e) => {
          setFormState?.((prev: object) => ({
            ...prev,
            email: e.target.value,
          }));
        }}
        labelText="Email"
        value={email ?? ''}
      />
    </Section>
  );
}

function Step2() {
  const { setFormState, formState } = useStepContext();
  const { city, state } = formState || {};
  useStepFocus('#city');
  return (
    <Section className="step-container">
      <Heading className="step-heading">Step 2</Heading>
      <div className="step-form-items">
        <TextInput
          id="city"
          onChange={(e) => {
            setFormState((prev: object) => ({
              ...prev,
              city: e.target.value,
            }));
          }}
          labelText="City"
          value={city ?? ''}
        />
        <TextInput
          id="state"
          onChange={(e) => {
            setFormState((prev: object) => ({
              ...prev,
              state: e.target.value,
            }));
          }}
          labelText="State"
          value={state ?? ''}
        />
      </div>
    </Section>
  );
}

function Step3() {
  // Example showing how to get step state via hook
  const { formState } = useStepContext();
  return (
    <Section className="step-container">
      <Heading className="step-heading">Step 3</Heading>
      <div>
        Form state
        <CodeSnippet type="multi">
          {JSON.stringify(formState, null, 2)}
        </CodeSnippet>
      </div>
    </Section>
  );
}
