// packages/ibm-products/src/patterns/CreateTearsheet/example/components/CreateTearsheetStep.tsx
/**
 * Copyright IBM Corp. 2021, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  useEffect,
  PropsWithChildren,
  isValidElement,
  forwardRef,
  RefObject,
  useRef,
} from 'react';
import { Heading, Section, FormGroup, Grid, Column } from '@carbon/react';
import cx from 'classnames';
import { useStepContext } from '@carbon/utilities-react';

const blockClass = 'create-tearsheet-step';

// Default values for props
const defaults = {
  hasFieldset: true,
  includeStep: true,
};

type fieldsetLegendTextProps =
  | {
      hasFieldset: false;
      fieldsetLegendText?: string;
      fieldsetLegendId?: React.ReactNode;
    }
  | {
      hasFieldset?: true;
      fieldsetLegendText?: string;
      fieldsetLegendId?: React.ReactNode;
    };

interface CreateTearsheetStepBaseProps extends PropsWithChildren {
  children?: React.ReactNode;
  className?: string;
  description?: React.ReactNode;
  subtitle?: string;
  title: React.ReactNode;
  label?: string;
  secondaryLabel?: string;
  onMount?: () => void;
  disableSubmit?: boolean;
  onNext?: () => Promise<void>;
  onPrevious?: () => void;
  primaryFocusElement?: string;
  includeStep?: boolean;
  introStep?: boolean;
  invalid?: boolean;
  hideSteps?: boolean;
}

type CreateTearsheetStepProps = CreateTearsheetStepBaseProps &
  fieldsetLegendTextProps;

export const CreateTearsheetStep = forwardRef<
  HTMLDivElement,
  CreateTearsheetStepProps
>(
  (
    {
      children,
      className,
      description,
      subtitle,
      title,
      label,
      secondaryLabel,
      onMount,
      disableSubmit,
      onNext,
      onPrevious,
      primaryFocusElement,
      fieldsetLegendText,
      fieldsetLegendId,
      hasFieldset = defaults.hasFieldset,
      includeStep = defaults.includeStep,
      introStep,
      invalid,
      ...rest
    },
    ref
  ) => {
    const localRef = useRef<HTMLDivElement>(null);
    const stepRef = ref || localRef;
    const { currentStep, totalSteps } = useStepContext();

    useEffect(() => {
      if (onMount) {
        onMount();
      }
    }, [onMount]);

    useEffect(() => {
      if (primaryFocusElement) {
        const element = document.querySelector(
          primaryFocusElement
        ) as HTMLElement;
        setTimeout(() => {
          element?.focus();
        });
      }
    }, [primaryFocusElement, currentStep]);

    const renderDescription = () => {
      if (description) {
        if (typeof description === 'string') {
          return <p className={`${blockClass}__description`}>{description}</p>;
        }
        if (isValidElement(description)) {
          return (
            <div className={`${blockClass}__description`}>{description}</div>
          );
        }
      }
      return null;
    };

    // Don't render the step at all if includeStep is false
    if (!includeStep) {
      return null;
    }

    return (
      <div ref={stepRef as RefObject<HTMLDivElement>}>
        <Grid
          {...rest}
          className={cx(blockClass, className, {
            [`${blockClass}--visible-step`]: includeStep,
          })}
        >
          <Column xlg={12} lg={12} md={8} sm={4}>
            <Heading className={`${blockClass}__title`}>{title}</Heading>

            {subtitle && (
              <h5 className={`${blockClass}__subtitle`}>{subtitle}</h5>
            )}

            {renderDescription()}
          </Column>

          <Column span={100}>
            {hasFieldset ? (
              <FormGroup
                legendText={fieldsetLegendText}
                className={`${blockClass}__fieldset`}
                legendId={fieldsetLegendId}
              >
                {children}
              </FormGroup>
            ) : (
              <div className={`${blockClass}__content`}>{children}</div>
            )}
          </Column>
        </Grid>
      </div>
    );
  }
);

CreateTearsheetStep.displayName = 'CreateTearsheetStep';

// packages/ibm-products-web-components/examples/create-tearsheet/src/components/create-tearsheet-step.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import '@carbon/web-components/es/components/grid/index.js';
import styles from '../create-tearsheet.scss?lit';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';

const blockClass = 'c4p--create-tearsheet';
const stepBlockClass = `${blockClass}__step`;

/**
 * CreateTearsheetStep component for web components
 */
@customElement('create-tearsheet-step')
export class CreateTearsheetStep extends LitElement {
  @property({ type: String })
  title = '';

  @property({ type: String })
  subtitle = '';

  @property({ type: String })
  description = '';

  @property({ type: Boolean, attribute: 'has-fieldset' })
  hasFieldset = false;

  @property({ type: String, attribute: 'fieldset-legend-text' })
  fieldsetLegendText = '';

  @property({ type: Boolean, attribute: 'intro-layout' })
  introLayout = false;

  render() {
    return html`
      <section class="${stepBlockClass}">
        <div class="${blockClass}__step-header">
          <h2 class="${blockClass}__step-title">${this.title}</h2>
          ${this.subtitle
            ? html`
                <p class="${blockClass}__step-subtitle">${this.subtitle}</p>
              `
            : ''}
          ${this.description
            ? html`
                <p class="${blockClass}__step-description">
                  ${this.description}
                </p>
              `
            : ''}
          <div class="${blockClass}__step-description">
            <slot name="description"></slot>
          </div>
        </div>

        <div class="${blockClass}__step-body">
          ${this.hasFieldset
            ? html`
                <fieldset class="${blockClass}__step-fieldset">
                  <legend>${this.fieldsetLegendText}</legend>
                  <div class="${blockClass}__step-item">
                    <slot></slot>
                  </div>
                </fieldset>
              `
            : html`
                <div
                  class="${blockClass}__step-content${
                    this.introLayout
                      ? ` ${blockClass}__step-content--intro-layout`
                      : ''
                  }">
                  <div
                    class="${blockClass}__step-item${
                      this.introLayout
                        ? ` ${blockClass}__step-item--intro-layout`
                        : ''
                    }">
                    <slot></slot>
                  </div>
                </div>
              `}
        </div>
      </section>
    `;
  }

  static styles = styles;
}

export default CreateTearsheetStep;
