// packages/ibm-products/src/components/ActionSet/ActionSet.tsx
/**
 * Copyright IBM Corp. 2021, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Carbon and package components we use.
import { Button, ButtonSet, InlineLoading } from '@carbon/react';
// Import portions of React that are needed.
import React, { ComponentProps, PropsWithChildren } from 'react';
import { allPropTypes, prepareProps } from '../../global/js/utils/props-helper';

import { ButtonProps } from '@carbon/react';
// Other standard imports.
import PropTypes from 'prop-types';
import cx from 'classnames';
import { pkg } from '../../settings';
import { ButtonKind } from '@carbon/react';
import pconsole from '../../global/js/utils/pconsole';

const blockClass = `${pkg.prefix}--action-set`;
const componentName = 'ActionSet';

export const ButtonSizes = ['sm', 'md', 'lg', 'xl', '2xl'] as const;

export type ButtonSize = (typeof ButtonSizes)[number];

type ActionSetButtonProps = ComponentProps<typeof Button>;

const ActionSetButton = React.forwardRef(
  (
    {
      // The component props, in alphabetical order (for consistency).
      className,
      disabled,
      kind,
      label,
      loading,
      isExpressive = true,
      // Collect any other property values passed in.
      ...rest
    }: PropsWithChildren<ActionSetButtonProps>,
    ref
  ) => (
    <Button
      {
        // Pass through any other property values as HTML attributes.
        ...rest
      }
      isExpressive={isExpressive}
      className={cx(className, [
        `${blockClass}__action-button`,
        {
          [`${blockClass}__action-button--ghost`]:
            kind === 'ghost' || kind === 'danger--ghost',
          [`${blockClass}__action-button--expressive`]: isExpressive,
        },
      ])}
      disabled={disabled || loading || false}
      {...{ kind, ref }}
    >
      {label}
      {loading && <InlineLoading />}
    </Button>
  )
);

ActionSetButton.displayName = 'ActionSetButton';

ActionSetButton.propTypes = {
  /**@ts-ignore*/
  ...Button.PropTypes,
  kind: PropTypes.oneOf([
    'ghost',
    'danger--ghost',
    'secondary',
    'danger',
    'primary',
  ]),
  label: PropTypes.string,
  loading: PropTypes.bool,
};

const defaultKind = 'primary';

const willStack = (size, numberOfActions) =>
  size === 'sm' || (size === 'md' && numberOfActions > 2);

// Default values for props
const defaults = {
  size: 'md',
};

export interface ActionSetProps {
  /**
   * The action buttons to show. Each action is specified as an object
   * representation of a Carbon button.
   *
   * See https://react.carbondesignsystem.com/?path=/docs/components-button--default#component-api
   */
  actions: ButtonProps<React.ElementType>[];

  /**
   * The size of buttons to use for the actions. The allowed values are
   * those for the size prop of carbon Button. If this prop is specified, all
   * the buttons will be set to this size, overriding any 'size' values (if any)
   * supplied in the actions array (if any).
   */
  buttonSize?: ButtonSize;
  /**
   * An optional class or classes to be added to the outermost element.
   */
  className?: string;

  /**
   * The size of the action set. Different button arrangements are used at
   * different sizes, to make best use of the available space.
   */
  size?: ButtonSize;
}

export const validateActionSetProps = ({ actions, size }) => {
  if (actions && actions.length) {
    const problems = [] as string[];

    const stacking = willStack(size, actions.length);

    const countActions = (kind: ButtonKind) =>
      actions.filter(
        (action: ButtonProps<React.ElementType>) =>
          (action.kind || defaultKind) === kind
      ).length;

    const primaryActions = countActions('primary');
    const secondaryActions = countActions('secondary');
    const dangerActions = countActions('danger');
    const ghostActions = countActions('ghost') + countActions('danger--ghost');

    if (stacking && actions > 3) {
      problems.push(
        `you cannot have more than three actions in this size of ${componentName}`
      );
    }

    if (actions.length > 4) {
      problems.push(
        `you cannot have more than four actions in a ${componentName}`
      );
    }
    if (primaryActions > 1) {
      problems.push(
        `you cannot have more than one 'primary' action in a ${componentName}`
      );
    }

    if (ghostActions > 1) {
      problems.push(
        `you cannot have more than one 'ghost' action in a ${componentName}`
      );
    }

    if (stacking && actions > 1 && ghostActions > 0) {
      problems.push(
        `you cannot have a 'ghost' button in conjunction with other action types in this size of ${componentName}`
      );
    }

    if (
      actions >
      primaryActions + secondaryActions + dangerActions + ghostActions
    ) {
      problems.push(
        `you can only have 'primary', 'danger', 'secondary', 'ghost' and 'danger--ghost' buttons in a ${componentName}`
      );
    }
    return problems.length > 0
      ? pconsole.error(
          `Invalid prop \`actions\` supplied to \`${componentName}\`: ${problems.join(
            ', and '
          )}.`
        )
      : null;
  }
};

/**
 * An ActionSet presents a set of action buttons, constructed from bundles
 * of prop values and applying some layout rules. When the size is 'sm'
 * the buttons are stacked, and should only include primary and secondary
 * kinds. When the size is 'md' the buttons are stacked if there are three or
 * more. When the size is 'md' or 'lg', two buttons share the horizontal space.
 * When the size is 'lg', three or more buttons use a quarter of the available
 * horizontal space, and if the size is 'xlg' or 'max' the buttons always use
 * a quarter of the available horizontal space. If there is a ghost button,
 * it appears at the left side. If there is a primary button it appears at the
 * right.
 */
export const ActionSet = React.forwardRef<HTMLDivElement, ActionSetProps>(
  (
    {
      // The component props, in alphabetical order (for consistency).

      actions,
      buttonSize,
      className,
      size = defaults.size as ButtonSize,

      // Collect any other property values passed in.
      ...rest
    }: ActionSetProps,
    ref
  ) => {
    validateActionSetProps({ actions, size });
    const buttons = (actions && actions.slice?.(0)) || [];

    // We stack the buttons in a sm set, or if there are three or more in a md set.
    const stacking = willStack(size, buttons.length);

    // Order of button kinds: ghost first, then danger--ghost, then most other types,
    // then danger, and finally primary
    const buttonOrder = (kind) =>
      ({
        ghost: 1,
        'danger--ghost': 2,
        danger: 4,
        primary: 5,
      })[kind] ?? 3;

    // order the actions with ghost/ghost-danger buttons first and primary/danger buttons last
    // (or the opposite way if we're stacking)
    buttons.sort(
      (action1, action2) =>
        (buttonOrder(action1.kind || defaultKind) -
          buttonOrder(action2.kind || defaultKind)) *
        (stacking ? -1 : 1)
    );

    return (
      <ButtonSet
        {
          // Pass through any other property values as HTML attributes.
          ...rest
        }
        className={cx(
          blockClass,
          className,
          {
            [`${blockClass}--row-single`]: !stacking && buttons.length === 1,
            [`${blockClass}--row-double`]: !stacking && buttons.length === 2,
            [`${blockClass}--row-triple`]: !stacking && buttons.length === 3,
            [`${blockClass}--row-quadruple`]: !stacking && buttons.length >= 4,
            [`${blockClass}--stacking`]: stacking,
          },
          `${blockClass}--${size}`
        )}
        ref={ref}
        role="presentation"
        stacked={stacking}
      >
        {buttons.map((action, index) => {
          const actionProps = prepareProps(action, ['key']);
          return (
            <ActionSetButton
              key={action.key || index}
              {...actionProps}
              size={buttonSize}
            />
          );
        })}
      </ButtonSet>
    );
  }
);

ActionSet.displayName = componentName;

/**
 * A validator function to help validate the actions supplied for a particular
 * size of component. When the size is sm, or md with three actions, the
 * buttons will be stacked and a maximum of three buttons is applied with no
 * ghosts unless the ghost is the only button. Otherwise a maximum of four
 * buttons with a maximum of one ghost is applied. In either case, a maximum
 * of one primary button is allowed.
 * @param sizeFn An optional function which will be passed all the props and
 * returns the size that the component should be treated as being: if not
 * provided, a 'size' prop is used to determine the size of the component.
 * @returns null if the actions meet the requirements, or an Error object with
 * an explanatory message.
 */

ActionSet.propTypes = {
  /**
   * The action buttons to show. Each action is specified as an
   * object with optional fields 'label' to supply the button label, 'kind'
   * to select the button kind (must be 'primary', 'secondary' or 'ghost'),
   * 'loading' to display a loading indicator, and 'onClick' to receive
   * notifications when the button is clicked. Additional fields in the object
   * will be passed to the Button component, and these can include 'disabled',
   * 'ref', 'className', and any other Button props. Any other fields in the
   * object will be passed through to the button element as HTML attributes.
   *
   * See https://react.carbondesignsystem.com/?path=/docs/components-button--default#component-api
   */
  actions: allPropTypes([
    PropTypes.arrayOf(
      PropTypes.shape({
        /**@ts-ignore*/
        ...Button.propTypes,
        kind: PropTypes.oneOf([
          'ghost',
          'danger--ghost',
          'secondary',
          'danger',
          'primary',
        ]),
        label: PropTypes.string,
        loading: PropTypes.bool,
        // we duplicate this Button prop to improve the DocGen here
        /**@ts-ignore*/
        onClick: Button.propTypes.onClick,
      })
    ),
  ]),

  /**
   * The size of buttons to use for the actions. The allowed values are
   * those for the size prop of carbon Button. If this prop is specified, all
   * the buttons will be set to this size, overriding any 'size' values (if any)
   * supplied in the actions array (if any).
   */
  /**@ts-ignore*/
  buttonSize: Button.propTypes.size,

  /**
   * An optional class or classes to be added to the outermost element.
   */
  className: PropTypes.string,

  /**
   * The size of the action set. Different button arrangements are used at
   * different sizes, to make best use of the available space.
   */
  size: PropTypes.oneOf(['sm', 'md', 'lg', 'xl', '2xl']),
};

// packages/ibm-products-web-components/examples/create-full-page/src/components/action-set.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element';
import '@carbon/web-components/es/components/button/index.js';
import '@carbon/web-components/es/components/button/button-set.js';

const blockClass = 'action-set';

export type ButtonKind =
  | 'primary'
  | 'secondary'
  | 'danger'
  | 'ghost'
  | 'danger--ghost';

export type ButtonSize = 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface ActionButton {
  key?: string;
  label: string;
  kind?: ButtonKind;
  onClick?: (event: Event) => void;
  disabled?: boolean;
  loading?: boolean;
}

const componentName = 'ActionSet';
const defaultKind: ButtonKind = 'primary';

/**
 * Validates ActionSet props and logs warnings for invalid configurations
 */
function validateActionSetProps(actions: ActionButton[], size: ButtonSize): void {
  if (actions && actions.length) {
    const problems: string[] = [];

    const willStack = (s: ButtonSize, numberOfActions: number): boolean =>
      s === 'sm' || (s === 'md' && numberOfActions > 2);

    const stacking = willStack(size, actions.length);

    const countActions = (kind: ButtonKind) =>
      actions.filter((action) => (action.kind || defaultKind) === kind).length;

    const primaryActions = countActions('primary');
    const secondaryActions = countActions('secondary');
    const dangerActions = countActions('danger');
    const ghostActions = countActions('ghost') + countActions('danger--ghost');

    if (stacking && actions.length > 3) {
      problems.push(
        `you cannot have more than three actions in this size of ${componentName}`
      );
    }

    if (actions.length > 4) {
      problems.push(
        `you cannot have more than four actions in a ${componentName}`
      );
    }

    if (primaryActions > 1) {
      problems.push(
        `you cannot have more than one 'primary' action in a ${componentName}`
      );
    }

    if (ghostActions > 1) {
      problems.push(
        `you cannot have more than one 'ghost' action in a ${componentName}`
      );
    }

    if (stacking && actions.length > 1 && ghostActions > 0) {
      problems.push(
        `you cannot have a 'ghost' button in conjunction with other action types in this size of ${componentName}`
      );
    }

    if (
      actions.length >
      primaryActions + secondaryActions + dangerActions + ghostActions
    ) {
      problems.push(
        `you can only have 'primary', 'danger', 'secondary', 'ghost' and 'danger--ghost' buttons in a ${componentName}`
      );
    }

    if (problems.length > 0) {
      console.warn(
        `Invalid prop \`actions\` supplied to \`${componentName}\`: ${problems.join(
          ', and '
        )}.`
      );
    }
  }
}

/**
 * ActionSet component for web components
 */
@customElement('action-set')
export class ActionSet extends LitElement {
  /**
   * Array of action buttons
   */
  @property({ type: Array })
  actions: ActionButton[] = [];

  /**
   * Button size
   */
  @property({ type: String, attribute: 'button-size' })
  buttonSize: ButtonSize = 'lg';

  /**
   * Size of the action set
   */
  @property({ type: String })
  size: ButtonSize = 'md';

  // Disable shadow DOM to use Carbon styles
  createRenderRoot() {
    return this;
  }

  private willStack(size: ButtonSize, numberOfActions: number): boolean {
    return size === 'sm' || (size === 'md' && numberOfActions > 2);
  }

  private buttonOrder(kind?: ButtonKind): number {
    const order: Record<string, number> = {
      ghost: 1,
      'danger--ghost': 2,
      danger: 4,
      primary: 5,
    };
    return order[kind || 'primary'] ?? 3;
  }

  private getSortedActions(): ActionButton[] {
    const buttons = [...this.actions];
    const stacking = this.willStack(this.size, buttons.length);

    // Sort actions with ghost/ghost-danger buttons first and primary/danger buttons last
    // (or the opposite way if we're stacking)
    buttons.sort(
      (action1, action2) =>
        (this.buttonOrder(action1.kind) - this.buttonOrder(action2.kind)) *
        (stacking ? -1 : 1)
    );

    return buttons;
  }

  private handleButtonClick(action: ActionButton, event: Event) {
    if (action.onClick && !action.disabled && !action.loading) {
      action.onClick(event);
    }
  }

  render() {
    if (!this.actions || this.actions.length === 0) {
      return html``;
    }

    // Validate actions configuration
    validateActionSetProps(this.actions, this.size);

    const stacking = this.willStack(this.size, this.actions.length);
    const sortedActions = this.getSortedActions();

    const classes = {
      [blockClass]: true,
      [`${blockClass}--row-single`]: !stacking && this.actions.length === 1,
      [`${blockClass}--row-double`]: !stacking && this.actions.length === 2,
      [`${blockClass}--row-triple`]: !stacking && this.actions.length === 3,
      [`${blockClass}--row-quadruple`]: !stacking && this.actions.length >= 4,
      [`${blockClass}--stacking`]: stacking,
      [`${blockClass}--${this.size}`]: true,
    };

    return html`
      <div class="${classMap(classes)}" role="presentation">
        <cds-button-set ?stacked="${stacking}">
          ${sortedActions.map(
            (action, index) => html`
              <cds-button
                class="${blockClass}__action-button ${action.kind === 'ghost' ||
                action.kind === 'danger--ghost'
                  ? `${blockClass}__action-button--ghost`
                  : ''}"
                kind="${action.kind || 'primary'}"
                size="${this.buttonSize}"
                ?disabled="${action.disabled || action.loading}"
                @click="${(e: Event) => this.handleButtonClick(action, e)}"
              >
                ${action.label}
                ${action.loading
                  ? html`<cds-inline-loading></cds-inline-loading>`
                  : ''}
              </cds-button>
            `
          )}
        </cds-button-set>
      </div>
    `;
  }
}
