// packages/ibm-products/src/components/Coachmark/CoachmarkTagline.tsx
/**
 * Copyright IBM Corp. 2023, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Import portions of React that are needed.
import React from 'react';

// Other standard imports.
import PropTypes from 'prop-types';
import cx from 'classnames';
import { Close, Idea } from '@carbon/react/icons';
import { Button } from '@carbon/react';
import { useCoachmark } from './utils/context';
import { getDevtoolsProps } from '../../global/js/utils/devtools';
import { pkg /*, carbon */ } from '../../settings';

// The block part of our conventional BEM class names (blockClass__E--M).
const blockClass = `${pkg.prefix}--coachmark-tagline`;
const componentName = 'CoachmarkTagline';

const defaults = {
  closeIconDescription: 'Close',
  onClose: () => {},
  theme: 'light',
};

interface CoachmarkTaglineProps {
  /**
   * Tooltip text and aria label for the Close button icon.
   */
  closeIconDescription?: string;
  /**
   * Function to call when the close button is clicked.
   */
  onClose?: () => void;
  /**
   * Determines the theme of the component.
   */
  theme?: 'light' | 'dark';
  /**
   * The title of the tagline.
   */
  title: string;
}

/**
 * DO NOT USE. This component is for the exclusive use
 * of other Onboarding components.
 */
export let CoachmarkTagline = React.forwardRef<
  HTMLDivElement,
  CoachmarkTaglineProps
>(
  (
    {
      closeIconDescription = defaults.closeIconDescription,
      onClose = defaults.onClose,
      theme = defaults.theme,
      title,
      ...rest
    },
    ref
  ) => {
    const coachmark = useCoachmark();

    return (
      <div
        {
          // Pass through any other property values as HTML attributes.
          ...rest
        }
        className={cx(
          blockClass,
          `${blockClass}__${theme}`,
          coachmark?.isOpen && `${blockClass}--is-open`
        )}
        ref={ref}
        {...getDevtoolsProps(componentName)}
      >
        <button
          // {...rest}
          className={`${blockClass}__cta`}
          type="button"
          {...coachmark?.buttonProps}
        >
          <div className={`${blockClass}__idea`}>
            <Idea size={16} />
          </div>
          <div>{title}</div>
        </button>
        <div className={`${blockClass}--close-btn-container`}>
          <Button
            kind="ghost"
            size="sm"
            renderIcon={Close}
            iconDescription={closeIconDescription}
            hasIconOnly
            className={`${blockClass}--close-btn`}
            onClick={onClose}
          />
        </div>
      </div>
    );
  }
);

// Return a placeholder if not released and not enabled by feature flag
CoachmarkTagline = pkg.checkComponentEnabled(CoachmarkTagline, componentName);

// The display name of the component, used by React. Note that displayName
// is used in preference to relying on function.name.
CoachmarkTagline.displayName = componentName;

// The types and DocGen commentary for the component props,
// in alphabetical order (for consistency).
// See https://www.npmjs.com/package/prop-types#usage.
CoachmarkTagline.propTypes = {
  /**
   * Tooltip text and aria label for the Close button icon.
   */
  closeIconDescription: PropTypes.string,
  /**
   * Function to call when the close button is clicked.
   */
  onClose: PropTypes.func,
  /**
   * Determines the theme of the component.
   */
  theme: PropTypes.oneOf(['light', 'dark']),
  /**
   * The title of the tagline.
   */
  title: PropTypes.string.isRequired,
};

// packages/ibm-products-web-components/src/components/coachmark/coachmark-tagline/coachmark-tagline.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../../globals/settings';
import HostListenerMixin from '@carbon/web-components/es/globals/mixins/host-listener.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import styles from './coachmark-tagline.scss?lit';
import Close16 from '@carbon/icons/es/close/16.js';
import Idea16 from '@carbon/icons/es/idea/16.js';
import '@carbon/web-components/es/components/button/button.js';
import iconLoader from '@carbon/web-components/es/globals/internal/icon-loader';

const blockClass = `${prefix}--coachmark-tagline`;

/**
 * DO NOT USE. This component is for the exclusive use
 * of other Onboarding components.
 *
 * Coachmark tagline component.
 *
 * @element c4p-coachmark-tagline
 * @fires c4p-coachmark-tagline-close - Custom event fired when close button is clicked
 * @fires c4p-coachmark-tagline-cta-click - Custom event fired when tagline CTA is clicked
 */
@customElement(`${prefix}-coachmark-tagline`)
class CDSCoachmarkTagline extends HostListenerMixin(LitElement) {
  /**
   * Tooltip text and aria label for the Close button icon.
   */
  @property({ type: String, attribute: 'close-icon-description' })
  closeIconDescription = 'Close';

  /**
   * The title of the tagline.
   */
  @property({ type: String })
  title = '';

  /**
   * Whether the tagline is open.
   */
  @property({ type: Boolean, reflect: true, attribute: 'open' })
  open = false;

  firstUpdated() {
    this.classList.add(blockClass);
    if (this.open) {
      this.classList.add(`${blockClass}--open`);
    }
  }
  /**
   * Handles the close button click event.
   */
  private _handleClose() {
    const closeEvent = new CustomEvent(`${prefix}-coachmark-tagline-close`, {
      bubbles: true,
      composed: true,
      detail: {},
    });
    this.dispatchEvent(closeEvent);
  }

  /**
   * Handles the CTA button click event.
   */
  private _handleCtaClick(event: Event) {
    const ctaClickEvent = new CustomEvent(
      `${prefix}-coachmark-tagline-cta-click`,
      {
        bubbles: true,
        composed: true,
        detail: { originalEvent: event },
      }
    );
    this.dispatchEvent(ctaClickEvent);
  }

  /**
   * Handles the CTA button double click event.
   */
  private _handleCtaDoubleClick(event: Event) {
    const ctaDoubleClickEvent = new CustomEvent(
      `${prefix}-coachmark-tagline-cta-dblclick`,
      {
        bubbles: true,
        composed: true,
        detail: { originalEvent: event },
      }
    );
    this.dispatchEvent(ctaDoubleClickEvent);
  }

  render() {
    return html`
      <button
        class="${blockClass}__cta"
        kind="ghost"
        size="sm"
        @click="${this._handleCtaClick}"
        @dblclick="${this._handleCtaDoubleClick}"
      >
        ${iconLoader(Idea16, { slot: 'icon' })} ${this.title}
      </button>
      <div class="${blockClass}--close-btn-container">
        <cds-button
          kind="ghost"
          size="sm"
          tooltip-text="${this.closeIconDescription}"
          has-icon-only
          class="${blockClass}--close-btn"
          @click="${this._handleClose}"
        >
          ${iconLoader(Close16, { slot: 'icon' })}
        </cds-button>
      </div>
    `;
  }

  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  static styles = styles;
}
export default CDSCoachmarkTagline;
