// packages/ibm-products-web-components/examples/single-add-select/src/single-add-select.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { customElement, state } from 'lit/decorators.js';

import '@carbon/web-components/es/components/button/index.js';
import '@carbon/web-components/es/components/notification/toast-notification.js';

import '../../../src/components/tearsheet/index';
import '../../../src/components/add-select/add-select/add-select';
import '../../../src/components/add-select/add-select-body/add-select-body';
import '../../../src/components/add-select/add-select-list/add-select-list';
import '../../../src/components/add-select/add-select-item/add-select-item';

import styles from './single-add-select.scss?lit';

// Sample data for the example
// const sampleItems = [
//   {
//     id: '1',
//     title: 'Kansas',
//     value: 'kansas',
//   },
//   {
//     id: '2',
//     title: 'Texas',
//     value: 'texas',
//   },
//   {
//     id: '3',
//     title: 'Florida',
//     value: 'florida',
//   },
// ];

// Sample data for the example with hierarchy
const sampleItems =[
            {
              id: '1',
              title: 'Kansas',
              value: 'kansas',
            },
            {
              id: '2',
              title: 'Texas',
              value: 'texas',
            },
            {
              id: '3',
              title: 'Florida',
              value: 'florida',
            },
            {
              id: '4',
              title: 'California',
              value: 'california',
              children: {
                entries: [
                  {
                    id: '5',
                    title: 'Los Angeles',
                    value: 'la',
                    children: {
                      entries: [
                        {
                          id: '6',
                          title: 'Beverly Hills',
                          value: 'bh',
                        },
                        {
                          id: '7',
                          title: 'Malibu',
                          value: 'malibu',
                          children: {
                            entries: [
                              {
                                id: '8',
                                title: 'Malibu Rd',
                                value: 'malibu-rd',
                              },
                            ],
                          },
                        },
                      ],
                    },
                  },
                ],
              },
            },
          ];

@customElement('single-add-select-example')
export class SingleAddSelectExample extends LitElement {
  static styles = styles;

  @state()
  private _open: boolean = false;

  @state()
  private _showNotification: boolean = false;

  @state()
  private _selectedItem: string = '';

  @state()
  private _searchTerm: string = '';

  @state()
  private _filteredItems = sampleItems;

  private _openAddSelect() {
    this._open = true;
    this._searchTerm = '';
    this._filteredItems = sampleItems;
    this._selectedItem = '';
  }

  private _handleClose() {
    this._open = false;
  }

  private _handleItemSelect(event: CustomEvent) {
    // Update selected item when an item is selected
    const { itemId, selected } = event.detail;
    console.log( event.detail)  
    if (selected) {
      this._selectedItem = itemId;
    } 
    console.log(this._selectedItem)  
  }

  private _handleSubmit() {
     if (this._selectedItem) {
        this._handleClose();
        this._showNotification = true;
        setTimeout(() => {
          this._showNotification = false;
        }, 3000);
      }
      
  }

  private _handleSearch(event: CustomEvent) {
    this._searchTerm = event.detail.searchTerm.toLowerCase();
    
    if (this._searchTerm) {
      this._filteredItems = sampleItems.filter(item =>
        item.title.toLowerCase().includes(this._searchTerm) 
      );
    } else {
      this._filteredItems = sampleItems;
    }
  }

  private _onNotificationClose() {
    this._showNotification = false;
  }

  render() {
    const selectedItemData = sampleItems.find(item => item.id === this._selectedItem);

    return html`
      <div class="example-container">
        <h3>Single Add Select Pattern Example</h3>
        <p>Click the button below to open the single add select dialog.</p>
        
        <cds-button
          type="button"
          kind="primary"
          size="md"
          @click="${this._openAddSelect}"
        >
          Select an item
        </cds-button>

        ${this._showNotification
          ? html`
              <cds-toast-notification
                kind="success"
                title="Item selected"
                subtitle="You selected: ${selectedItemData?.title}"
                timeout="3000"
                @cds-notification-closed="${this._onNotificationClose}"
              >
              </cds-toast-notification>
            `
          : ''}

        <!-- Single Add Select Pattern using Tearsheet -->
        ${this._open ? html`
          <c4p-add-select>
            <c4p-tearsheet
              ?open=${this._open}
              width="narrow"
              @c4p-tearsheet-closed="${this._handleClose}"
            >
              <!-- Header -->
              <h3 slot="title">Select category</h3>
              <div slot="description">Choose one category from the list below </div>

              <!-- Body with Add Select Content -->
              <c4p-add-select-body
                global-search-label="Search categories"
                global-search-placeholder="Search..."
                items-label="Categories"
                search-results-title="Search results"
                no-results-title="No results found"
                no-results-description="Try adjusting your search"
                .itemCount="${this._filteredItems.length}"
                @c4p-add-select-body-search="${this._handleSearch}"
              >
                <c4p-add-select-list
                >
                  ${this._filteredItems.map(
                    (item) => {
                      const hasChildren = !!item.children;
                      console.log(`Rendering item "${item.title}", hasChildren:`, hasChildren, item.children);
                      return html`
                        <c4p-add-select-item
                          item-id="${item.id}"
                          title="${item.title}"
                          value="${item.value}"
                          ?has-children="${hasChildren}"
                          ?selected="${this._selectedItem === item.id}"
                          @c4p-add-select-item-select="${this._handleItemSelect}"
                        >
                        </c4p-add-select-item>`;
                    }
                  )}
                </c4p-add-select-list>
              </c4p-add-select-body>

              <!-- Footer with Action Buttons -->
              <cds-button
                slot="actions"
                kind="secondary"
                @click="${this._handleClose}"
              >
                Cancel
              </cds-button>
              <cds-button
                slot="actions"
                kind="primary"
                @click="${this._handleSubmit}"
                ?disabled="${!this._selectedItem}"
              >
                Select
              </cds-button>
            </c4p-tearsheet>
          </c4p-add-select>
        ` : ''}
      </div>
    `;
  }
}

export default SingleAddSelectExample;

// packages/ibm-products/src/patterns/AddSelect/example/components/SingleAddSelect/SingleAddSelect.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  useState,
  useMemo,
  useEffect,
} from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { ToastNotification } from '@carbon/react';
import { AddSelect } from '../../../../../components/AddSelect/next';
import { AddSelectData, AddSelectItem } from '@carbon/ibm-products-primitives';
import { Tearsheet } from '../../../../../components/Tearsheet/next';
// import './SingleAddSelect.scss';

const blockClass = `single-add-select-pattern`;

/**
 * SingleAddSelect Pattern - A complete pattern with Tearsheet for single selection (first level only)
 */

export interface SingleAddSelectProps {
  /**
   * Whether the tearsheet is open
   */
  open: boolean;
  /**
   * Callback to set open state
   */
  setOpen: (open: boolean) => void;
  /**
   * Array of items to display (only first level will be shown)
   */
  items: AddSelectItem[];
  /**
   * Callback when an item is submitted
   */
  onSubmit?: (itemId: string, value: string) => void;
  /**
   * Title for the tearsheet
   */
  title?: string;
  /**
   * Description for the tearsheet
   */
  description?: ReactNode;
  /**
   * Label for items section
   */
  itemsLabel?: string;
  /**
   * Global search label
   */
  globalSearchLabel?: string;
  /**
   * Global search placeholder
   */
  globalSearchPlaceholder?: string;
  /**
   * Search results title
   */
  searchResultsTitle?: string;
  /**
   * No results title
   */
  noResultsTitle?: string;
  /**
   * No results description
   */
  noResultsDescription?: string;
  /**
   * Primary button text
   */
  primaryButtonText?: string;
  /**
   * Secondary button text
   */
  secondaryButtonText?: string;
  /**
   * Success notification title
   */
  successNotificationTitle?: string;
  /**
   * Success notification subtitle template
   */
  successNotificationSubtitle?: string;
  /**
   * Optional class name
   */
  className?: string;
}

export const SingleAddSelect = forwardRef<HTMLDivElement, SingleAddSelectProps>(
  (
    {
      open,
      setOpen,
      items,
      onSubmit,
      title = 'Select category',
      description = 'Choose one category from the list below',
      itemsLabel = 'Categories',
      globalSearchLabel = 'Search',
      globalSearchPlaceholder = 'Search...',
      searchResultsTitle = 'Search results',
      noResultsTitle = 'No results found',
      noResultsDescription = 'Try adjusting your search or browse categories',
      primaryButtonText = 'Select',
      secondaryButtonText = 'Cancel',
      successNotificationTitle = 'Item Selected',
      successNotificationSubtitle = 'Selected: {value}',
      className,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    // Initialize data manager
    const dataManager = useMemo(() => new AddSelectData(), []);

    const [searchTerm, setSearchTerm] = useState('');
    const [selectedId, setSelectedId] = useState<string>();
    const [selectedValue, setSelectedValue] = useState<string>('');
    const [filteredItems, setFilteredItems] = useState<AddSelectItem[]>([]);
    const [currentItems, setCurrentItems] = useState<AddSelectItem[]>([]);
    const [showNotification, setShowNotification] = useState(false);
    const [notificationMessage, setNotificationMessage] = useState('');

    // Initialize data manager with items
    useEffect(() => {
      dataManager.setItems(items);
      const rootItems = dataManager.getItems();
      setFilteredItems(rootItems);
      setCurrentItems(rootItems);
    }, [items, dataManager]);

    // Reset state when tearsheet opens
    useEffect(() => {
      if (open) {
        setSelectedId(undefined);
        setSelectedValue('');
        setSearchTerm('');
        const rootItems = dataManager.getItems();
        setFilteredItems(rootItems);
        setCurrentItems(rootItems);
      }
    }, [open, dataManager]);

    // Handle item selection
    const handleItemSelect = (
      itemId: string,
      selected: boolean,
      value: string
    ) => {
      if (selected) {
        setSelectedId(itemId);
        setSelectedValue(value);
        dataManager.setSelectedItems(itemId, true);
      } else {
        setSelectedId(undefined);
        setSelectedValue('');
        dataManager.clearSelections();
      }
    };

    // Handle search
    const handleSearch = (term: string) => {
      setSearchTerm(term);

      if (term) {
        const results = dataManager.search(term, {
          caseSensitive: false,
          searchFields: ['title', 'value'],
        });
        setFilteredItems(results);
      } else {
        setFilteredItems(currentItems);
      }
    };

    // Create selected items set
    const selectedItems = useMemo(() => {
      const set = new Set<string>();
      if (selectedId) {
        set.add(selectedId);
      }
      return set;
    }, [selectedId]);

    // Handle close
    const handleClose = () => {
      setOpen(false);
    };

    // Handle submit
    const handleSubmit = () => {
      if (selectedId) {
        onSubmit?.(selectedId, selectedValue);
        handleClose();

        // Show success notification
        const message = successNotificationSubtitle.replace(
          '{value}',
          selectedValue
        );
        setNotificationMessage(message);
        setShowNotification(true);
      }
    };

    return (
      <>
        <AddSelect
          onItemSelect={handleItemSelect}
          selectedItems={selectedItems}
        >
          <Tearsheet
            ref={ref}
            open={open}
            onClose={handleClose}
            variant="narrow"
            className={cx(blockClass, className)}
            {...rest}
          >
            <Tearsheet.Header hideCloseButton>
              <Tearsheet.HeaderContent title={title}>
                <p slot="description">{description}</p>
              </Tearsheet.HeaderContent>
            </Tearsheet.Header>

            <Tearsheet.Body>
              <Tearsheet.MainContent>
                <AddSelect.Body
                  itemsLabel={itemsLabel}
                  globalSearchLabel={globalSearchLabel}
                  globalSearchPlaceholder={globalSearchPlaceholder}
                  searchResultsTitle={searchResultsTitle}
                  itemCount={filteredItems.length}
                  onSearch={handleSearch}
                >
                  <AddSelect.Content>
                    {filteredItems.length > 0 ? (
                      filteredItems.map((item) => {
                        return (
                          <AddSelect.Row
                            key={item.id}
                            itemId={item.id}
                            title={item.title || ''}
                            subtitle={item.subtitle}
                            value={item.value || ''}
                            icon={item.icon}
                            disabled={item.disabled}
                          />
                        );
                      })
                    ) : (
                      <div className={`${blockClass}__no-results`}>
                        <h4>{noResultsTitle}</h4>
                        <p>{noResultsDescription}</p>
                      </div>
                    )}
                  </AddSelect.Content>
                </AddSelect.Body>
              </Tearsheet.MainContent>
            </Tearsheet.Body>

            <Tearsheet.Footer
              actions={[
                {
                  kind: 'secondary',
                  label: secondaryButtonText,
                  onClick: handleClose,
                },
                {
                  kind: 'primary',
                  label: primaryButtonText,
                  onClick: handleSubmit,
                  disabled: !selectedId,
                },
              ]}
            />
          </Tearsheet>
        </AddSelect>

        {showNotification && (
          <ToastNotification
            aria-label="closes notification"
            caption={new Date().toLocaleTimeString()}
            className="notification"
            kind="success"
            lowContrast
            onClose={() => setShowNotification(false)}
            role="status"
            statusIconDescription="notification"
            subtitle={notificationMessage}
            title={successNotificationTitle}
          />
        )}
      </>
    );
  }
);

SingleAddSelect.propTypes = {
  className: PropTypes.string,
  description: PropTypes.node,
  globalSearchLabel: PropTypes.string,
  globalSearchPlaceholder: PropTypes.string,
  items: PropTypes.array.isRequired,
  itemsLabel: PropTypes.string,
  noResultsDescription: PropTypes.string,
  noResultsTitle: PropTypes.string,
  onSubmit: PropTypes.func,
  open: PropTypes.bool.isRequired,
  primaryButtonText: PropTypes.string,
  searchResultsTitle: PropTypes.string,
  secondaryButtonText: PropTypes.string,
  setOpen: PropTypes.func.isRequired,
  successNotificationSubtitle: PropTypes.string,
  successNotificationTitle: PropTypes.string,
  title: PropTypes.string,
};

SingleAddSelect.displayName = 'SingleAddSelect';
