// packages/ibm-products-web-components/src/components/add-select/add-select-item-panel.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import '@carbon/web-components/es/components/icon-button/index.js';
import { iconLoader } from '@carbon/web-components/es/globals/internal/icon-loader.js';
import Close16 from '@carbon/icons/es/close/16';
import { prefix } from '../../globals/settings';
import type { AddSelectItem } from '@carbon/ibm-products-utilities';
import styles from './add-select-item-panel.scss?lit';

const blockClass = `${prefix}--add-select__next`;

/**
 * Add Select Item Panel — side panel displaying detailed information about an item.
 * CSS modifier `${blockClass}__item-summary-panel--open` is added when `open` is true,
 * enabling CSS-driven slide-in/out transitions.
 * @element c4p-add-select-item-panel
 * @slot default - Highest priority: replaces all body rendering when populated
 * @slot render-item - Medium priority: receives item for custom rendering
 * @fires c4p-add-select-item-panel-close - Fired when close icon is clicked
 */
@customElement(`${prefix}-add-select-item-panel`)
class CDSAddSelectItemPanel extends LitElement {
  /**
   * Panel title
   */
  @property({ type: String })
  title = 'Item details';

  /**
   * Item data (set via JS property)
   */
  @property({ attribute: false })
  item: AddSelectItem | null = null;

  /**
   * Controls panel visibility via CSS modifier class (enables CSS transitions)
   */
  @property({ type: Boolean, reflect: true })
  open = false;

  /**
   * Accessible label for the close icon button
   */
  @property({ type: String, attribute: 'close-icon-description' })
  closeIconDescription = 'Close';

  private _handleClose() {
    this.dispatchEvent(
      new CustomEvent(
        (this.constructor as typeof CDSAddSelectItemPanel).eventClose,
        { bubbles: true, cancelable: true, composed: true }
      )
    );
  }

  private _renderDefaultContent() {
    const { item } = this;
    if (!item) {
      return nothing;
    }
    const { itemDetails } = item;
    if (
      !itemDetails ||
      !Array.isArray(itemDetails) ||
      itemDetails.length === 0
    ) {
      return nothing;
    }
    return html`
      ${itemDetails.map(
        ({ label, value: val }) => html`
          <div class="${blockClass}__item-summary-panel-entry">
            <p class="${blockClass}__item-summary-panel-entry-title">
              ${label}
            </p>
            <p class="${blockClass}__item-summary-panel-entry-body">
              ${String(val)}
            </p>
          </div>
        `
      )}
    `;
  }

  render() {
    const { title, open, closeIconDescription } = this;

    const panelClasses = classMap({
      [`${blockClass}__item-summary-panel`]: true,
      [`${blockClass}__item-summary-panel--open`]: open,
    });

    return html`
      <div class=${panelClasses}>
        <!-- Header -->
        <div class="${blockClass}__item-summary-panel-header">
          <p class="${blockClass}__item-summary-panel-title">${title}</p>
          <cds-icon-button
            label=${closeIconDescription}
            kind="ghost"
            size="sm"
            class="${blockClass}__item-summary-panel-close"
            @click=${this._handleClose}
          >
            ${iconLoader(Close16, { slot: 'icon' })}
          </cds-icon-button>
        </div>

        <!-- Body: priority 1=default slot, 2=render-item slot, 3=default template -->
        <div class="${blockClass}__item-summary-panel-body">
          <slot>
            <slot name="render-item"> ${this._renderDefaultContent()} </slot>
          </slot>
        </div>
      </div>
    `;
  }

  /**
   * The name of the custom event fired when the close icon is clicked.
   */
  static get eventClose() {
    return `${prefix}-add-select-item-panel-close`;
  }

  static styles = styles;
}

export default CDSAddSelectItemPanel;

// packages/ibm-products/src/components/AddSelect/next/AddSelectItemPanel.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  isValidElement,
} from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { IconButton, type IconButtonProps } from '@carbon/react';
import { Close } from '@carbon/react/icons';
import type { AddSelectItem } from '@carbon/ibm-products';
import { blockClass } from './context';

/**
 * ----------------
 * AddSelectItemPanel
 * ----------------
 */

export interface AddSelectItemPanelProps {
  /**
   * Panel title
   */
  title?: string;
  /**
   * Item data
   */
  item?: AddSelectItem;
  /**
   * Close button handler
   */
  onClose?: () => void;
  /**
   * Close button aria-label
   */
  closeIconDescription?: string;
  /**
   * Custom content - takes highest priority
   */
  children?: ReactNode;
  /**
   * Custom template for rendering the entire panel body content
   * Takes precedence over default rendering
   */
  renderItem?: (item: AddSelectItem) => ReactNode;
  /**
   * Optional class name
   */
  className?: string;
  /**
   * Controls visibility of the panel by toggling the
   * `${blockClass}__item-summary-panel--open` CSS modifier class.
   * Use this instead of conditional rendering when you need CSS-driven
   * slide-in/out transitions.
   */
  open?: boolean;
  /**
   * Additional props to pass to the close IconButton
   */
  closeIconButtonProps?: Omit<
    IconButtonProps,
    'label' | 'onClick' | 'kind' | 'size' | 'className' | 'children'
  >;
}

/**
 * AddSelectItemPanel - Displays detailed information about a specific item
 * @example
 * ```jsx
 * <AddSelect.ItemPanel
 *   title="Item details"
 *   item={item}
 *   onClose={handleClose}
 *   closeIconDescription="Close details"
 * />
 * ```
 */
const AddSelectItemPanel = forwardRef<HTMLDivElement, AddSelectItemPanelProps>(
  (
    {
      title = 'Item details',
      item,
      onClose,
      closeIconDescription = 'Close',
      children,
      renderItem,
      className,
      open,
      closeIconButtonProps,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const panelClasses = cx(`${blockClass}__item-summary-panel`, className, {
      [`${blockClass}__item-summary-panel--open`]: open,
    });

    // Default content rendering — renders only labelled itemDetails tuples.
    // Only renders when itemDetails is the preferred Array<{ label, value }>
    // form. Legacy Record-shaped itemDetails (used by custom renderers) are
    // intentionally skipped to avoid rendering internal keys in the UI.
    const defaultContent = () => {
      if (!item) {
        return null;
      }

      const { itemDetails } = item;

      if (
        !itemDetails ||
        !Array.isArray(itemDetails) ||
        itemDetails.length === 0
      ) {
        return null;
      }

      return (
        <>
          {itemDetails.map(({ label, value: val }) => (
            <div
              key={label}
              className={`${blockClass}__item-summary-panel-entry`}
            >
              <p className={`${blockClass}__item-summary-panel-entry-title`}>
                {label}
              </p>
              <p className={`${blockClass}__item-summary-panel-entry-body`}>
                {String(val)}
              </p>
            </div>
          ))}
        </>
      );
    };

    // Render content based on priority
    const renderItemContent = () => {
      // Priority 1: children takes highest precedence
      if (children) {
        return children;
      }

      // Priority 2: renderItem
      if (renderItem && item) {
        return renderItem(item);
      }

      // Priority 3: default template
      return defaultContent();
    };

    return (
      <div className={panelClasses} ref={ref} {...rest}>
        {/* Header with title and close button */}
        <div className={`${blockClass}__item-summary-panel-header`}>
          <p className={`${blockClass}__item-summary-panel-title`}>{title}</p>
          {onClose && (
            <IconButton
              label={closeIconDescription}
              onClick={onClose}
              kind="ghost"
              size="sm"
              autoAlign
              className={`${blockClass}__item-summary-panel-close`}
              {...closeIconButtonProps}
            >
              <Close size={16} />
            </IconButton>
          )}
        </div>

        {/* Body content */}
        <div className={`${blockClass}__item-summary-panel-body`}>
          {renderItemContent()}
        </div>
      </div>
    );
  }
);

AddSelectItemPanel.propTypes = {
  children: PropTypes.node,
  className: PropTypes.string,
  /**@ts-ignore */
  closeIconButtonProps: PropTypes.object,
  closeIconDescription: PropTypes.string,
  /**@ts-ignore */
  item: PropTypes.object,
  /**@ts-ignore */
  onClose: PropTypes.func,
  open: PropTypes.bool,
  /**@ts-ignore */
  renderItem: PropTypes.func,
  title: PropTypes.string,
};

AddSelectItemPanel.displayName = 'AddSelectItemPanel';

export default AddSelectItemPanel;
