// packages/ibm-products-web-components/src/components/coachmark/coachmark-beacon/coachmark-beacon.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, PropertyValues, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { prefix } from '../../../globals/settings';
import HostListenerMixin from '@carbon/web-components/es/globals/mixins/host-listener.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import styles from './coachmark-beacon.scss?lit';
import '@carbon/web-components/es/components/button/button.js';
import '@carbon/web-components/es/components/icon-button/index.js';
import { BEACON_KIND } from './defs';

const blockClass = `${prefix}--coachmark-beacon`;

type ButtonProps = Record<string, any>;

/**
 * CoachmarkBeacon.
 *
 * @element c4p-coachmark-beacon
 * */
@customElement(`${prefix}-coachmark-beacon`)
class CDSCoachmarkBeacon extends HostListenerMixin(LitElement) {
  /**
   * What style of beacon.
   * BEACON_KIND is an enum from the Coachmark and can be used for this value.
   * @see {@link BEACON_KIND}
   */
  @property({ reflect: true })
  kind?: BEACON_KIND = BEACON_KIND.DEFAULT;

  /**
   * The aria label.
   */
  @property({ type: String, reflect: true })
  label = '';
  /**
   * button props
   */
  @property({ type: Object })
  buttonProps: ButtonProps = {};

  private applyButtonProps(buttonProps?: ButtonProps) {
    const button = this.shadowRoot?.querySelector('cds-button');
    if (!button || !buttonProps) {return;}

    Object.entries(buttonProps).forEach(([key, value]) => {
      if (value === false || value == null) {
        button.removeAttribute(key);
      } else {
        button.setAttribute(key, value === true ? '' : value);
      }
    });
  }

  updated(_changedProperties: PropertyValues) {
    if (_changedProperties.has('buttonProps')) {
      this.applyButtonProps(this.buttonProps);
    }
  }

  render() {
    const classes = classMap({
      [`${blockClass}`]: true,
      [`${blockClass}-${this.kind}`]: true,
    });

    return html`
      <div class=${classes}>
        <cds-button
          class="${blockClass}__target"
          type="button"
          @click=${this.buttonProps?.onClick}
        >
            <svg
              class="${blockClass}__center"
              aria-label=${this.label}
              width="76"
              height="76"
              viewBox="0 0 76 76"
              slot: 'icon',
            >
              <title>${this.label}</title>
              <circle r="1" cx="38" cy="38"></circle>
            </svg>
 
        </cds-button>
      </div>
    `;
  }
  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };
  static styles = styles;
}
export default CDSCoachmarkBeacon;

// packages/ibm-products/src/components/CoachmarkBeacon/CoachmarkBeacon.tsx
/**
 * Copyright IBM Corp. 2023, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Import portions of React that are needed.
import React from 'react';

// Other standard imports.
import PropTypes from 'prop-types';
import cx from 'classnames';
import { BEACON_KIND, useCoachmark } from '../Coachmark';

import { getDevtoolsProps } from '../../global/js/utils/devtools';
import { pkg /*, carbon */ } from '../../settings';

// The block part of our conventional BEM class names (blockClass__E--M).
const blockClass = `${pkg.prefix}--coachmark-beacon`;
const componentName = 'CoachmarkBeacon';

const defaults = {
  kind: 'default',
};

interface CoachmarkBeaconProps {
  /**
   * Optional class name for this component.
   */
  className?: string;
  /**
   * What style of beacon.
   * BEACON_KIND is an exported enum from the Coachmark and can be used for this value.
   * @see {@link BEACON_KIND}
   */
  kind?: BEACON_KIND;
  /**
   * The aria label.
   */
  label: string;
}

/**
 * Use beacon for the target prop of a Coachmark component.
 */
export let CoachmarkBeacon = React.forwardRef<
  HTMLDivElement,
  CoachmarkBeaconProps
>(({ label, className, kind = defaults.kind, ...rest }, ref) => {
  const coachmark = useCoachmark();
  if (!coachmark) {
    return (
      <div>
        CoachmarkBeacon is to be use exclusively within the target prop of
        Coachmark
      </div>
    );
  }
  return (
    <span
      {
        // Pass through any other property values as HTML attributes.
        ...rest
      }
      className={cx(blockClass, `${blockClass}-${kind}`, className)}
      ref={ref}
      {...getDevtoolsProps(componentName)}
      role="tooltip"
    >
      <button
        tabIndex={0}
        type="button"
        {...coachmark.buttonProps}
        aria-label={label}
        className={`${blockClass}__target`}
      >
        <svg className={`${blockClass}__center`}>
          <title>{label}</title>
          <circle r={1} cx={38} cy={38} />
        </svg>
      </button>
    </span>
  );
});

// Return a placeholder if not released and not enabled by feature flag
CoachmarkBeacon = pkg.checkComponentEnabled(CoachmarkBeacon, componentName);

// The display name of the component, used by React. Note that displayName
// is used in preference to relying on function.name.
CoachmarkBeacon.displayName = componentName;

// The types and DocGen commentary for the component props,
// in alphabetical order (for consistency).
// See https://www.npmjs.com/package/prop-types#usage.
CoachmarkBeacon.propTypes = {
  /**
   * Optional class name for this component.
   */
  className: PropTypes.string,
  /**
   * What style of beacon.
   * BEACON_KIND is an exported enum from the Coachmark and can be used for this value.
   * @see {@link BEACON_KIND}
   */
  kind: PropTypes.oneOf(['default' as BEACON_KIND.DEFAULT]),
  /**
   * The aria label.
   */
  label: PropTypes.string.isRequired,
};
