// packages/ibm-products-web-components/examples/add-select/src/single-add-select/single-add-select-with-hierarchy.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, LitElement } from 'lit';
import { customElement, state } from 'lit/decorators.js';

import '@carbon/web-components/es/components/button/index.js';
import '@carbon/web-components/es/components/notification/toast-notification.js';

import '../../../../src/components/tearsheet-preview/index';
import '../../../../src/components/add-select/index';
import { AddSelectData } from '@carbon/ibm-products-utilities';
import type { AddSelectItem } from '@carbon/ibm-products-utilities';

import styles from './single-add-select-with-hierarchy.scss?lit';

// Hierarchical data matching the React SingleAddSelectWithHierarchy preview
const sampleItems: AddSelectItem[] = [
  { id: '1', title: 'Kansas', value: 'kansas' },
  { id: '2', title: 'Texas', value: 'texas' },
  { id: '3', title: 'Florida', value: 'florida' },
  {
    id: '4',
    title: 'California',
    value: 'california',
    children: {
      entries: [
        {
          id: '5',
          title: 'Los Angeles',
          value: 'la',
          children: {
            entries: [
              { id: '6', title: 'Beverly Hills', value: 'bh' },
              {
                id: '7',
                title: 'Malibu',
                value: 'malibu',
                children: {
                  entries: [{ id: '8', title: 'Malibu Rd', value: 'malibu-rd' }],
                },
              },
            ],
          },
        },
        { id: '9', title: 'San Francisco', value: 'sf' },
      ],
    },
  },
  {
    id: '10',
    title: 'New York',
    value: 'ny',
    children: {
      entries: [
        { id: '11', title: 'Manhattan', value: 'manhattan' },
        { id: '12', title: 'Brooklyn', value: 'brooklyn' },
      ],
    },
  },
];

interface NavStackEntry {
  items: AddSelectItem[];
  parentId: string;
  parentTitle: string;
}

@customElement('single-add-select-with-hierarchy-example')
export class SingleAddSelectWithHierarchyExample extends LitElement {
  static styles = styles;

  private dataManager = new AddSelectData();

  @state() private _open = false;
  @state() private _showNotification = false;
  @state() private _selectedItemId = '';
  @state() private _selectedValue = '';
  @state() private _filteredItems: AddSelectItem[] = [];
  @state() private _currentItems: AddSelectItem[] = [];
  @state() private _navigationStack: NavStackEntry[] = [];

  constructor() {
    super();
    this.dataManager.setItems(sampleItems);
    this._currentItems = this.dataManager.getItems();
    this._filteredItems = this.dataManager.getItems();
  }

  private _openAddSelect() {
    this.dataManager.clearSelections();
    this._selectedItemId = '';
    this._selectedValue = '';
    this._navigationStack = [];
    this._currentItems = this.dataManager.getItems();
    this._filteredItems = this.dataManager.getItems();
    this._open = true;
  }

  private _handleClose() {
    this._open = false;
  }

  private _handleSearch(e: CustomEvent) {
    const term = e.detail.searchTerm.toLowerCase();
    if (term) {
      this._filteredItems = this.dataManager.search(term, {
        caseSensitive: false,
        searchFields: ['title', 'value'],
      });
    } else {
      this._filteredItems = this._currentItems;
    }
  }

  private _handleItemSelect(e: CustomEvent) {
    const { itemId, selected, value } = e.detail;
    if (selected) {
      this._selectedItemId = itemId;
      this._selectedValue = value;
      this.dataManager.setSelectedItems(itemId, true);
    } else {
      this._selectedItemId = '';
      this._selectedValue = '';
      this.dataManager.clearSelections();
    }
  }

  private _handleNavigate(e: CustomEvent) {
    const { itemId, title, parentId } = e.detail;
    const children = this.dataManager.getItemChildren(itemId);
    if (children.length === 0) return;

    this._navigationStack = [
      ...this._navigationStack,
      { items: this._currentItems, parentId: parentId || '', parentTitle: title },
    ];
    this._currentItems = children;
    this._filteredItems = children;
    this._selectedItemId = '';
    this._selectedValue = '';
    this.dataManager.clearSelections();
  }

  private _handleBreadcrumbClick(e: CustomEvent) {
    const { index } = e.detail;
    const levelsBack = this._navigationStack.length - index;
    let stack = [...this._navigationStack];
    let items = this._currentItems;

    for (let i = 0; i < levelsBack; i++) {
      const prev = stack[stack.length - 1];
      stack = stack.slice(0, -1);
      items = prev.items;
    }
    this._navigationStack = stack;
    this._currentItems = items;
    this._filteredItems = items;
    this._selectedItemId = '';
    this._selectedValue = '';
    this.dataManager.clearSelections();
  }

  private _getBreadcrumbPath() {
    const path: Array<{ id: string; title: string }> = [
      { id: 'root', title: 'Categories' },
    ];
    this._navigationStack.forEach((entry) => {
      path.push({ id: entry.parentId, title: entry.parentTitle });
    });
    return path;
  }

  private _handleSubmit() {
    if (!this._selectedItemId) return;
    this._handleClose();
    this._showNotification = true;
    setTimeout(() => { this._showNotification = false; }, 3000);
  }

  render() {
    const breadcrumbPath = this._getBreadcrumbPath();

    return html`
      <div class="example-container">
        <h3>Single Add Select – With Hierarchy</h3>
        <p>Click the button below to open the single add select dialog with hierarchical navigation.</p>

        <cds-button kind="primary" @click="${this._openAddSelect}">
          Select a category
        </cds-button>

        ${this._showNotification
          ? html`
              <cds-toast-notification
                kind="success"
                title="Item selected"
                subtitle="Selected: ${this._selectedValue}"
                timeout="3000"
                @cds-notification-closed="${() => { this._showNotification = false; }}"
              ></cds-toast-notification>
            `
          : ''}

        ${this._open
          ? html`
              <c4p-add-select ?multi=${false}>
                <c4p-preview-tearsheet
                  ?open=${this._open}
                  variant="narrow"
                  @c4p-preview-tearsheet-closed="${this._handleClose}"
                >
                  <c4p-tearsheet-header hide-close-button slot="header">
                    <c4p-tearsheet-header-content title="Select category">
                      <div slot="description">Choose one category from the list below</div>
                    </c4p-tearsheet-header-content>
                  </c4p-tearsheet-header>

                  <c4p-tearsheet-body>
                    <c4p-add-select-body
                      slot="main-content"
                      global-search-label="Search categories"
                      global-search-placeholder="Search..."
                      items-label="Categories"
                      search-results-title="Search results"
                      .itemCount="${this._filteredItems.length}"
                      .path="${breadcrumbPath}"
                      @c4p-add-select-body-search="${this._handleSearch}"
                      @c4p-add-select-body-breadcrumb-click="${this._handleBreadcrumbClick}"
                    >
                      <c4p-add-select-column hide-search>
                        ${this._filteredItems.length > 0
                          ? this._filteredItems.map(
                              (item) => html`
                                <c4p-add-select-row
                                  item-id="${item.id}"
                                  title="${item.title}"
                                  value="${item.value}"
                                  ?has-children="${this.dataManager.hasChildren(item.id)}"
                                  ?selected="${this._selectedItemId === item.id}"
                                  @c4p-add-select-row-select="${this._handleItemSelect}"
                                  @c4p-add-select-row-navigate="${this._handleNavigate}"
                                ></c4p-add-select-row>
                              `
                            )
                          : html`
                              <div class="no-results">
                                <h4 class="no-results__title">No results found</h4>
                                <p class="no-results__description">Try adjusting your search or browse categories</p>
                              </div>
                            `}
                      </c4p-add-select-column>
                    </c4p-add-select-body>
                  </c4p-tearsheet-body>

                  <c4p-tearsheet-footer slot="footer">
                    <div class="action-buttons">
                      <cds-button kind="secondary" @click="${this._handleClose}">Cancel</cds-button>
                      <cds-button
                        kind="primary"
                        @click="${this._handleSubmit}"
                        ?disabled="${!this._selectedItemId}"
                      >Select</cds-button>
                    </div>
                  </c4p-tearsheet-footer>
                </c4p-preview-tearsheet>
              </c4p-add-select>
            `
          : ''}
      </div>
    `;
  }
}

export default SingleAddSelectWithHierarchyExample;

// packages/ibm-products/src/patterns/AddSelect/example/components/SingleAddSelectWithHierarchy/SingleAddSelectWithHierarchy.tsx
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, {
  forwardRef,
  ForwardedRef,
  ReactNode,
  useState,
  useMemo,
  useEffect,
} from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { ToastNotification } from '@carbon/react';
import { AddSelect } from '../../../../../components/AddSelect/next';
import { AddSelectData, AddSelectItem } from '@carbon/ibm-products-primitives';
import { Tearsheet } from '../../../../../components/Tearsheet/next';
import './SingleAddSelectWithHierarchy.scss';

const blockClass = `single-add-select-with-hierarchy-pattern`;

/**
 * SingleAddSelectWithHierarchy Pattern - A complete pattern with Tearsheet for single selection with hierarchical navigation
 */

export interface SingleAddSelectWithHierarchyProps {
  /**
   * Whether the tearsheet is open
   */
  open: boolean;
  /**
   * Callback to set open state
   */
  setOpen: (open: boolean) => void;
  /**
   * Array of hierarchical items to display
   */
  items: AddSelectItem[];
  /**
   * Callback when an item is submitted
   */
  onSubmit?: (itemId: string, value: string) => void;
  /**
   * Title for the tearsheet
   */
  title?: string;
  /**
   * Description for the tearsheet
   */
  description?: ReactNode;
  /**
   * Label for items section
   */
  itemsLabel?: string;
  /**
   * Global search label
   */
  globalSearchLabel?: string;
  /**
   * Global search placeholder
   */
  globalSearchPlaceholder?: string;
  /**
   * Search results title
   */
  searchResultsTitle?: string;
  /**
   * No results title
   */
  noResultsTitle?: string;
  /**
   * No results description
   */
  noResultsDescription?: string;
  /**
   * Root breadcrumb title
   */
  rootBreadcrumbTitle?: string;
  /**
   * Primary button text
   */
  primaryButtonText?: string;
  /**
   * Secondary button text
   */
  secondaryButtonText?: string;
  /**
   * Success notification title
   */
  successNotificationTitle?: string;
  /**
   * Success notification subtitle template
   */
  successNotificationSubtitle?: string;
  /**
   * Optional class name
   */
  className?: string;
}

interface NavigationStackItem {
  items: AddSelectItem[];
  parentId: string;
  parentTitle: string;
}

export const SingleAddSelectWithHierarchy = forwardRef<
  HTMLDivElement,
  SingleAddSelectWithHierarchyProps
>(
  (
    {
      open,
      setOpen,
      items,
      onSubmit,
      title = 'Select category',
      description = 'Choose one category from the list below',
      itemsLabel = 'Categories',
      globalSearchLabel = 'Search',
      globalSearchPlaceholder = 'Search...',
      searchResultsTitle = 'Search results',
      noResultsTitle = 'No results found',
      noResultsDescription = 'Try adjusting your search or browse categories',
      rootBreadcrumbTitle = 'Categories',
      primaryButtonText = 'Select',
      secondaryButtonText = 'Cancel',
      successNotificationTitle = 'Item Selected',
      successNotificationSubtitle = 'Selected: {value}',
      className,
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    // Initialize data manager
    const dataManager = useMemo(() => new AddSelectData(), []);

    const [searchTerm, setSearchTerm] = useState('');
    const [selectedId, setSelectedId] = useState<string>();
    const [selectedValue, setSelectedValue] = useState<string>('');
    const [filteredItems, setFilteredItems] = useState<AddSelectItem[]>([]);
    const [currentItems, setCurrentItems] = useState<AddSelectItem[]>([]);
    const [navigationStack, setNavigationStack] = useState<
      NavigationStackItem[]
    >([]);
    const [showNotification, setShowNotification] = useState(false);
    const [notificationMessage, setNotificationMessage] = useState('');

    // Initialize data manager with items
    useEffect(() => {
      dataManager.setItems(items);
      const rootItems = dataManager.getItems();
      setFilteredItems(rootItems);
      setCurrentItems(rootItems);
    }, [items, dataManager]);

    // Reset state when tearsheet opens
    useEffect(() => {
      if (open) {
        setSelectedId(undefined);
        setSelectedValue('');
        setSearchTerm('');
        setNavigationStack([]);
        const rootItems = dataManager.getItems();
        setFilteredItems(rootItems);
        setCurrentItems(rootItems);
      }
    }, [open, dataManager]);

    // Handle item selection
    const handleItemSelect = (
      itemId: string,
      selected: boolean,
      value: string
    ) => {
      if (selected) {
        setSelectedId(itemId);
        setSelectedValue(value);
        dataManager.setSelectedItems(itemId, true);
      } else {
        setSelectedId(undefined);
        setSelectedValue('');
        dataManager.clearSelections();
      }
    };

    // Handle search
    const handleSearch = (term: string) => {
      setSearchTerm(term);

      if (term) {
        const results = dataManager.search(term, {
          caseSensitive: false,
          searchFields: ['title', 'value'],
        });
        setFilteredItems(results);
      } else {
        setFilteredItems(currentItems);
      }
    };

    // Handle navigation to children
    const handleNavigate = (
      itemId: string,
      title: string,
      parentId: string
    ) => {
      const children = dataManager.getItemChildren(itemId);

      if (children.length > 0) {
        setNavigationStack((prev) => [
          ...prev,
          {
            items: currentItems,
            parentId: parentId || '',
            parentTitle: title,
          },
        ]);

        setCurrentItems(children);
        setFilteredItems(children);
        setSearchTerm('');
        setSelectedId(undefined);
        setSelectedValue('');
      }
    };

    // Handle breadcrumb click
    const handleBreadcrumbClick = (index: number) => {
      const levelsToGoBack = navigationStack.length - index;

      if (levelsToGoBack > 0) {
        const newStack = navigationStack.slice(0, index);
        setNavigationStack(newStack);

        if (index === 0) {
          const rootItems = dataManager.getItems();
          setCurrentItems(rootItems);
          setFilteredItems(rootItems);
        } else {
          const targetLevel = navigationStack[index - 1];
          setCurrentItems(targetLevel.items);
          setFilteredItems(targetLevel.items);
        }

        setSearchTerm('');
        setSelectedId(undefined);
        setSelectedValue('');
      }
    };

    // Build breadcrumb path
    const breadcrumbPath = useMemo(() => {
      const path = [{ id: 'root', title: rootBreadcrumbTitle }];

      navigationStack.forEach((item) => {
        path.push({ id: item.parentId, title: item.parentTitle });
      });

      return path;
    }, [navigationStack, rootBreadcrumbTitle]);

    // Create selected items set
    const selectedItems = useMemo(() => {
      const set = new Set<string>();
      if (selectedId) {
        set.add(selectedId);
      }
      return set;
    }, [selectedId]);

    // Handle close
    const handleClose = () => {
      setOpen(false);
    };

    // Handle submit
    const handleSubmit = () => {
      if (selectedId) {
        onSubmit?.(selectedId, selectedValue);
        handleClose();

        // Show success notification
        const message = successNotificationSubtitle.replace(
          '{value}',
          selectedValue
        );
        setNotificationMessage(message);
        setShowNotification(true);
      }
    };

    return (
      <>
        <Tearsheet
          ref={ref}
          open={open}
          onClose={handleClose}
          variant="narrow"
          className={cx(blockClass, className)}
          {...rest}
        >
          <Tearsheet.Header hideCloseButton>
            <Tearsheet.HeaderContent title={title}>
              <p slot="description">{description}</p>
            </Tearsheet.HeaderContent>
          </Tearsheet.Header>

          <Tearsheet.Body>
            <Tearsheet.MainContent>
              <AddSelect
                multi={false}
                onItemSelect={handleItemSelect}
                selectedItems={selectedItems}
              >
                <AddSelect.Body
                  itemsLabel={itemsLabel}
                  globalSearchLabel={globalSearchLabel}
                  globalSearchPlaceholder={globalSearchPlaceholder}
                  searchResultsTitle={searchResultsTitle}
                  itemCount={filteredItems.length}
                  onSearch={handleSearch}
                  path={breadcrumbPath}
                  onBreadcrumbClick={handleBreadcrumbClick}
                >
                  <AddSelect.Content>
                    <AddSelect.Column onNavigate={handleNavigate}>
                      {filteredItems.length > 0 ? (
                        filteredItems.map((item) => {
                          const hasChildren = dataManager.hasChildren(item.id);

                          return (
                            <AddSelect.Row
                              key={item.id}
                              itemId={item.id}
                              title={item.title || ''}
                              subtitle={item.subtitle}
                              value={item.value || ''}
                              icon={item.icon}
                              disabled={item.disabled}
                              hasChildren={hasChildren}
                            />
                          );
                        })
                      ) : (
                        <div className={`${blockClass}__no-results`}>
                          <h4>{noResultsTitle}</h4>
                          <p>{noResultsDescription}</p>
                        </div>
                      )}
                    </AddSelect.Column>
                  </AddSelect.Content>
                </AddSelect.Body>
              </AddSelect>
            </Tearsheet.MainContent>
          </Tearsheet.Body>

          <Tearsheet.Footer
            actions={[
              {
                kind: 'secondary',
                label: secondaryButtonText,
                onClick: handleClose,
              },
              {
                kind: 'primary',
                label: primaryButtonText,
                onClick: handleSubmit,
                disabled: !selectedId,
              },
            ]}
          />
        </Tearsheet>

        {showNotification && (
          <ToastNotification
            aria-label="closes notification"
            caption={new Date().toLocaleTimeString()}
            className="notification"
            kind="success"
            lowContrast
            onClose={() => setShowNotification(false)}
            role="status"
            statusIconDescription="notification"
            subtitle={notificationMessage}
            title={successNotificationTitle}
          />
        )}
      </>
    );
  }
);

SingleAddSelectWithHierarchy.propTypes = {
  className: PropTypes.string,
  description: PropTypes.node,
  globalSearchLabel: PropTypes.string,
  globalSearchPlaceholder: PropTypes.string,
  /**@ts-ignore */
  items: PropTypes.arrayOf(
    PropTypes.shape({
      children: PropTypes.shape({
        entries: PropTypes.array,
      }),
      disabled: PropTypes.bool,
      icon: PropTypes.node,
      id: PropTypes.string.isRequired,
      meta: PropTypes.node,
      subtitle: PropTypes.string,
      title: PropTypes.string,
      value: PropTypes.string,
    })
  ).isRequired,
  itemsLabel: PropTypes.string,
  noResultsDescription: PropTypes.string,
  noResultsTitle: PropTypes.string,
  /**@ts-ignore */
  onSubmit: PropTypes.func,
  open: PropTypes.bool.isRequired,
  primaryButtonText: PropTypes.string,
  rootBreadcrumbTitle: PropTypes.string,
  searchResultsTitle: PropTypes.string,
  secondaryButtonText: PropTypes.string,
  /**@ts-ignore */
  setOpen: PropTypes.func.isRequired,
  successNotificationSubtitle: PropTypes.string,
  successNotificationTitle: PropTypes.string,
  title: PropTypes.string,
};

SingleAddSelectWithHierarchy.displayName = 'SingleAddSelectWithHierarchy';
