// packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenFooter.tsx
/**
 * Copyright IBM Corp. 2024, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React, { useContext, useMemo, useRef, useState } from 'react';

import { pkg } from '../../settings';
import PropTypes from 'prop-types';

import {
  ActionType,
  disableButtonConfigType,
  InterstitialScreenContext,
} from './InterstitialScreen';
import { Button, InlineLoading, ModalFooter } from '@carbon/react';
import { clamp } from '../../global/js/utils/clamp';
import { ArrowRight } from '@carbon/react/icons';

type actionButtonRendererArgs = {
  handleGotoStep?: (value: number) => void;
  progStep?: number;
  stepCount?: number;
  disableButtonConfig?: disableButtonConfigType;
};

export interface InterstitialScreenFooterProps {
  /**
   * Provide an optional class to be applied to the containing node.
   */
  className?: string;
  /**
   * The label for the Previous button.
   */
  previousButtonLabel?: string;

  /**
   * The label for the skip button.
   */
  skipButtonLabel?: string;
  /**
   * The label for the start button.
   */
  startButtonLabel?: string;
  /**
   * The label for the Next button.
   */
  nextButtonLabel?: string;
  /**
   * This is an optional callback prop that allows to render your custom footer action buttons.
   * note: this is applicable when not using custom actionButtonRenderer
   */
  actionButtonRenderer?: (config: actionButtonRendererArgs) => React.ReactNode;

  /**
   * optional asynchronous callback on action button click
   */
  onAction?: (actionName: ActionType, config: actionButtonRendererArgs) => void;
}
const InterstitialScreenFooter = React.forwardRef<
  HTMLDivElement,
  InterstitialScreenFooterProps
>((props, ref) => {
  const {
    className = '',
    skipButtonLabel = 'Skip',
    previousButtonLabel = 'Back',
    nextButtonLabel = 'Next',
    startButtonLabel = 'Get Started',
    actionButtonRenderer,
    onAction,
  } = props;
  const blockClass = `${pkg.prefix}--interstitial-screen`;
  const {
    handleClose,
    progStep,
    handleGotoStep,
    stepCount,
    disableButtonConfig,
    isFullScreen,
  } = useContext(InterstitialScreenContext);
  const startButtonRef = useRef<HTMLElement | undefined>(undefined);
  const nextButtonRef = useRef<HTMLElement | undefined>(undefined);

  const [loadingAction, setLoadingAction] = useState('');

  const isMultiStep = !!stepCount;
  const progStepFloor = 0;
  const progStepCeil = stepCount - 1;

  const handleAction = async (actionType: ActionType) => {
    setLoadingAction(actionType);

    await onAction?.(actionType, {
      handleGotoStep,
      progStep,
      stepCount,
      disableButtonConfig,
    });

    setLoadingAction('');

    if (actionType === 'next' || actionType === 'back') {
      const stepDelta = actionType === 'next' ? 1 : -1;
      const targetStep = clamp(
        progStep + stepDelta,
        progStepFloor,
        progStepCeil
      );
      handleGotoStep?.(targetStep as number);
    } else {
      handleClose?.(actionType);
    }
  };

  // Usage
  const handleStart = () => handleAction('start');
  const handleSkip = () => handleAction('skip');
  const handleClickNext = () => handleAction('next');
  const handleClickPrev = () => handleAction('back');

  const getRenderIcon = useMemo(() => {
    if (loadingAction !== 'start' && isMultiStep && progStep === progStepCeil) {
      return { renderIcon: ArrowRight };
    }
    return {};
  }, [loadingAction, isMultiStep, progStep, progStepCeil]);

  const getFooterContent = () => (
    <div ref={ref} className={`${blockClass}--footer ${className}`}>
      {isMultiStep && skipButtonLabel !== '' && (
        <Button
          className={`${blockClass}--skip-btn`}
          kind="ghost"
          size="lg"
          title={skipButtonLabel}
          onClick={handleSkip}
          disabled={disableButtonConfig?.skip}
        >
          {skipButtonLabel}
          {loadingAction === 'skip' && <InlineLoading />}
        </Button>
      )}
      <div className={`${blockClass}--footer-controls`}>
        {isMultiStep && progStep > 0 && (
          <Button
            className={`${blockClass}--prev-btn`}
            kind="secondary"
            size="lg"
            title={previousButtonLabel}
            disabled={disableButtonConfig?.back}
            onClick={handleClickPrev}
          >
            {previousButtonLabel}
            {loadingAction === 'back' && <InlineLoading />}
          </Button>
        )}

        {isMultiStep && progStep < progStepCeil && (
          <Button
            className={`${blockClass}--next-btn`}
            renderIcon={loadingAction !== 'next' ? ArrowRight : null}
            ref={nextButtonRef}
            size="lg"
            title={nextButtonLabel}
            disabled={disableButtonConfig?.next}
            onClick={handleClickNext}
          >
            {nextButtonLabel}
            {loadingAction === 'next' && <InlineLoading />}
          </Button>
        )}
        {((isMultiStep && progStep === progStepCeil) || !isMultiStep) && (
          <Button
            className={`${blockClass}--start-btn`}
            ref={startButtonRef}
            size="lg"
            title={startButtonLabel}
            disabled={disableButtonConfig?.start}
            onClick={handleStart}
            {...getRenderIcon}
          >
            {startButtonLabel}
            {loadingAction === 'start' && <InlineLoading />}
          </Button>
        )}
      </div>
    </div>
  );
  if (actionButtonRenderer) {
    return (
      <div className={`${blockClass}--footer`}>
        {actionButtonRenderer({
          handleGotoStep,
          progStep,
          stepCount,
          disableButtonConfig,
        })}
      </div>
    );
  }

  return isFullScreen ? (
    getFooterContent()
  ) : (
    <ModalFooter ref={ref}>{getFooterContent()}</ModalFooter>
  );
});

export default InterstitialScreenFooter;

InterstitialScreenFooter.propTypes = {
  /**
   * This is an optional callback prop that allows to render your custom footer action buttons.
   */
  actionButtonRenderer: PropTypes.func,
  /**
   * Provide an optional class to be applied to the containing node.
   */
  className: PropTypes.string,

  /**
   * The label for the Next button.
   */
  nextButtonLabel: PropTypes.string,
  /**
   * optional asynchronous callback on action button click (skip, previous, next and start)
   * note: this is applicable when not using custom actionButtonRenderer
   */
  onAction: PropTypes.func,
  /**
   * The label for the Previous button.
   *
   */
  previousButtonLabel: PropTypes.string,
  /**
   * The label for the skip button.
   */
  skipButtonLabel: PropTypes.string,
  /**
   * The label for the start button.
   */
  startButtonLabel: PropTypes.string,
};

// packages/ibm-products-web-components/src/components/interstitial-screen/interstitial-screen-footer.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, nothing } from 'lit';
import { property, state } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import HostListenerMixin from '@carbon/web-components/es/globals/mixins/host-listener.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import '@carbon/web-components/es/components/button/index.js';
import styles from './interstitial-screen-footer.scss?lit';
import { interstitialDetailsSignal } from './interstitial-screen-context';
import { SignalWatcher } from '@lit-labs/signals';
import '@carbon/web-components/es/components/inline-loading/inline-loading.js';
import { CDSModalFooter } from '@carbon/web-components/es/index.js';
import ArrowRight from '@carbon/web-components/es/icons/arrow--right/16.js';

const blockClass = `${prefix}--interstitial-screen`;

export type ActionType = 'close' | 'start' | 'skip' | 'back' | 'next';

/**
 * interstitial-screen-footer for footer section
 * @element c4p-interstitial-screen-footer
 */
@customElement(`${prefix}-interstitial-screen-footer`)
class CDSInterstitialScreenFooter extends SignalWatcher(
  HostListenerMixin(CDSModalFooter)
) {
  /**
   * The label for the Next button.
   */
  @property({ reflect: true })
  nextButtonLabel: string = 'Next';
  /**
   * The label for the Previous button.
   */
  @property({ reflect: true })
  previousButtonLabel: string = 'Back';
  /**
   * The label for the skip button.
   */
  @property({ reflect: true })
  skipButtonLabel: string = 'Skip';
  /**
   * The label for the start button.
   */
  @property({ reflect: true })
  startButtonLabel = 'Get Started';

  /**
   * Enables support for asynchronous validation or user confirmation before proceeding
   * to the next interstitial step. When set to true, the component will wait for an external
   *  listener (e.g., a form validation or confirmation modal) to resolve the proceed() callback before continuing.
   * When asyncAction is true, you must listen for the eventOnBeforeAction event and
   * call the proceed() function (either synchronously or with a promise) to allow navigation.
   */
  @property({ type: Boolean, reflect: true, attribute: 'async-action' })
  asyncAction;

  @state()
  loadingAction;

  private _handleUserInitiatedClose(
    triggeredBy: EventTarget | null | ActionType
  ) {
    const init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      detail: {
        triggeredBy,
      },
    };
    if (
      this.dispatchEvent(
        new CustomEvent(
          (
            this.constructor as typeof CDSInterstitialScreenFooter
          ).eventBeforeClose,
          init
        )
      )
    ) {
      this.dispatchEvent(
        new CustomEvent(
          (this.constructor as typeof CDSInterstitialScreenFooter).eventClose,
          init
        )
      );
    }
  }

  private handleSkip = () => this.handleAction('skip');
  private handleStart = () => this.handleAction('start');
  private handleClickNext = () => this.handleAction('next');
  private handleClickPrev = () => this.handleAction('back');

  private handleAction = async (actionType: ActionType) => {
    this.loadingAction = actionType;

    const currentStep = interstitialDetailsSignal.get().currentStep;
    const stepCount = interstitialDetailsSignal.get().stepDetails.length;

    let resolvePromise;
    const proceedPromise = new Promise<boolean>((resolve) => {
      resolvePromise = resolve;
    });

    const customEvent = new CustomEvent(
      (
        this.constructor as typeof CDSInterstitialScreenFooter
      ).eventOnBeforeAction,
      {
        bubbles: true,
        composed: true,
        cancelable: true,
        detail: {
          step: currentStep,
          stepCount: stepCount,
          proceed: (allow: boolean | Promise<boolean>) => {
            Promise.resolve(allow).then(resolvePromise);
          },
        },
      }
    );

    const eventNotCanceled = this.dispatchEvent(customEvent);

    if (!eventNotCanceled) {
      return;
    }

    const canProceed = this.asyncAction ? await proceedPromise : true;

    this.loadingAction = '';

    if (canProceed) {
      const carouselAPI = interstitialDetailsSignal.get()?.carouselAPI;
      if (actionType == 'next') {
        carouselAPI.next();
      } else if (actionType === 'back') {
        carouselAPI.prev();
      } else {
        this._handleUserInitiatedClose?.(actionType);
      }
    }
  };

  getFooterContent() {
    const stepDetails = interstitialDetailsSignal.get().stepDetails;
    const currentStep = interstitialDetailsSignal.get().currentStep;
    const isMulti = stepDetails?.length > 0;
    const progStepCeil = stepDetails?.length - 1;
    return html`
      <div class="${blockClass}--footer">
        ${isMulti
          ? html`
              <cds-button
                class="${blockClass}--skip-btn"
                kind="ghost"
                size="lg"
                title="${this.skipButtonLabel}"
                @click="${this.handleSkip}"
                ?disabled="${interstitialDetailsSignal.get().disableActions
                  ?.skip}"
              >
                ${this.skipButtonLabel}
              </cds-button>
            `
          : ''}
        <div class="${blockClass}--footer-controls">
          ${isMulti && currentStep > 0
            ? html`
                <cds-button
                  class="${blockClass}--prev-btn"
                  kind="secondary"
                  size="lg"
                  title="${this.previousButtonLabel}"
                  ?disabled="${interstitialDetailsSignal.get().disableActions
                    ?.back}"
                  @click="${this.handleClickPrev}"
                >
                  ${this.previousButtonLabel}
                  ${this.loadingAction === 'back'
                    ? html` <cds-inline-loading slot="icon" aria-live="off">
                      </cds-inline-loading>`
                    : nothing}
                </cds-button>
              `
            : nothing}
          ${isMulti && currentStep < progStepCeil
            ? html`
                <cds-button
                  class="${blockClass}--next-btn"
                  kind="primary"
                  size="lg"
                  title="${this.nextButtonLabel}"
                  ?disabled="${interstitialDetailsSignal.get().disableActions
                    ?.next}"
                  @click="${this.handleClickNext}"
                >
                  ${this.nextButtonLabel}
                  ${this.loadingAction === 'next'
                    ? html` <cds-inline-loading slot="icon" aria-live="off">
                      </cds-inline-loading>`
                    : html` ${ArrowRight({ slot: 'icon' })}`}
                </cds-button>
              `
            : nothing}
          ${(isMulti && currentStep === progStepCeil) || !isMulti
            ? html`
                <cds-button
                  class="${blockClass}--start-btn"
                  kind="primary"
                  size="lg"
                  title="${this.startButtonLabel}"
                  ?disabled="${interstitialDetailsSignal.get().disableActions
                    ?.start}"
                  @click="${this.handleStart}"
                >
                  ${this.startButtonLabel}
                  ${this.loadingAction === 'start'
                    ? html` <cds-inline-loading slot="icon" aria-live="off">
                      </cds-inline-loading>`
                    : nothing}
                </cds-button>
              `
            : nothing}
        </div>
      </div>
    `;
  }

  render() {
    const isFullScreen = interstitialDetailsSignal.get().isFullScreen;
    return html`<slot>
      ${isFullScreen
        ? html`${this.getFooterContent()}`
        : html`<cds-modal-footer>
            ${this.getFooterContent()}
          </cds-modal-footer>`}
    </slot>`;
  }

  static styles = styles;

  /**
   * The name of the custom event fired before this tearsheet is being closed upon a user gesture.
   * Cancellation of this event stops the user-initiated action of closing this tearsheet.
   */
  static get eventBeforeClose() {
    return `${prefix}-interstitial-beingclosed`;
  }

  /**
   * The name of the custom event fired after this tearsheet is closed upon a user gesture.
   */
  static get eventClose() {
    return `${prefix}-interstitial-closed`;
  }

  /**
   * The name of the custom event fired just before the action.
   */
  static get eventOnBeforeAction() {
    return `${prefix}-on-before-action`;
  }
}
export default CDSInterstitialScreenFooter;
