// packages/ibm-products-web-components/src/components/import-modal/import-modal.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property, state } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import HostListenerMixin from '@carbon/web-components/es/globals/mixins/host-listener.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element.js';
import styles from './import-modal.scss?lit';
import '@carbon/web-components/es/components/modal/index';
import '@carbon/web-components/es/components/icon-button/index.js';
import '@carbon/web-components/es/components/button/index';
import '@carbon/web-components/es/components/text-input/index';
import '@carbon/web-components/es/components/file-uploader/demo-file-uploader';
import '@carbon/web-components/es/components/file-uploader/file-uploader-item';
import Add16 from '@carbon/web-components/es/icons/add/16.js';
import { ref } from 'lit/directives/ref.js';

const blockClass = `${prefix}--import-modal`;

export type FileType = {
  fetchError?: undefined | boolean;
  fileData?: File;
  fileSize?: number;
  iconDescription?: string;
  invalidFileType?: boolean;
  name: string;
  status?: 'uploading' | 'edit' | 'complete';
  uuid?: string;
  invalid?: boolean;
  errorBody?: string;
  errorSubject?: string;
};

/**
 * ImportModal.
 *
 * @element import-modal
 *
 * */

@customElement(`${prefix}-import-modal`)
class ImportModal extends HostListenerMixin(LitElement) {
  /**
   * The text displayed at the top of the modal
   */
  @property({ reflect: true })
  title;

  /**
   * Content that is displayed inside the modal
   */
  @property({ reflect: true })
  description;

  /**
   * Specify the text for the secondary button
   */
  @property({ reflect: true })
  secondaryButtonText;

  /**
   * Specify the text for the primary button
   */
  @property({ reflect: true })
  primaryButtonText;

  /**
   * Specify whether the Modal is currently open
   */
  @property({ reflect: true })
  open;

  /**
   * Placeholder for text input
   */
  @property({ reflect: true })
  inputPlaceholder;

  /**
   * Header to display above import by url
   */
  @property({ reflect: true })
  inputLabel;

  /**
   * ID for text input
   */
  @property({ reflect: true })
  inputId;

  /**
   * Button text for import by url button
   */
  @property({ reflect: true })
  inputButtonText;

  /**
   * Button icon for import by url button
   */
  @property({ reflect: true })
  inputButtonIcon;

  /**
   * Header for the drag and drop box
   */
  @property({ reflect: true })
  fileDropHeader;

  /**
   * Label for the drag and drop box
   */
  @property({ reflect: true })
  fileDropLabel;

  /**
   * Label that appears when a file is uploaded to show number of files (1 / 1)
   */
  @property({ reflect: true })
  fileUploadLabel;

  /**
   * Specify the types of files that this input should be able to receive
   */
  @property({ reflect: true })
  accept;

  /**
   * Optional error header to display specifically for a fetch error
   */
  @property({ reflect: true })
  fetchErrorHeader;

  /**
   * Optional error body to display specifically for a fetch error
   */
  @property({ reflect: true })
  fetchErrorBody;

  /**
   * The default message shown for an import error
   */
  @property({ reflect: true })
  defaultErrorBody;

  /**
   * The default header that is displayed to show an error message
   */
  @property({ reflect: true })
  defaultErrorHeader;

  /**
   * Optional error message to display specifically for a invalid file type error
   */
  @property({ reflect: true })
  invalidFileTypeErrorBody;

  /**
   * Optional error header to display specifically for a invalid file type error
   */
  @property({ reflect: true })
  invalidFileTypeErrorHeader;

  /**
   * Optional error message to display specifically for a max file size error
   */
  @property({ reflect: true })
  maxFileSizeErrorBody;

  /**
   * Optional error header to display specifically for a max file size error
   */
  @property({ reflect: true })
  maxFileSizeErrorHeader;

  /**
   * File size limit in bytes
   */
  @property({ reflect: true })
  maxFileSize;

  @state()
  files: FileType[] = [];

  @state()
  fileStatusString = '';

  @state()
  importUrl: string = '';

  /**
   * Handles `submit` in import modal.
   *
   */
  private submitHandler = () => {
    this.dispatchEvent(
      new CustomEvent('request-submit', {
        detail: this.files,
        bubbles: true,
        composed: true,
      })
    );
  };

  render() {
    let modalRef: HTMLElement | null = null;
    const isInvalidFileType = (file) => {
      const acceptSet = new Set(this.accept);
      const name = file.name;
      const mimeType = file.type;
      const extension = `.${name.split('.').pop()}`;
      if (
        acceptSet.has(mimeType) ||
        acceptSet.has(extension) ||
        this.accept.length === 0
      ) {
        return false;
      }
      return true;
    };

    const fetchFile = async (url) => {
      if (!url) {
        this.fileStatusString = 'No URL provided.';
        return;
      }

      const fileName = url.substring(url.lastIndexOf('/') + 1).split('?')[0];

      const pendingFile = {
        name: fileName,
        status: 'uploading',
        uuid: 'dummy',
      };

      try {
        const response = await fetch(this.importUrl);
        if (!response.ok || response.status !== 200) {
          throw new Error(`${response.status}`);
        }
        const blob = await response.blob();
        const fetchedFile: FileType = new File([blob], fileName, {
          type: blob.type,
        });
        fetchedFile.invalidFileType = isInvalidFileType(fetchedFile);
        fetchedFile.uuid = pendingFile.uuid;
        updateFiles([fetchedFile]);
      } catch (err) {
        const failedFile = {
          ...pendingFile,
          fetchError: true,
        };
        updateFiles([failedFile]);
      }
    };

    const updateFiles = (newFiles) => {
      const updatedFiles = newFiles.map((file) => {
        const newFile = {
          uuid: file.uuid,
          status: 'edit',
          iconDescription: 'invalidIconDescription',
          name: file.name,
          fileSize: file.size,
          invalidFileType: file.invalidFileType,
          fileData: file,
          fetchError: file.fetchError,
        } as FileType;

        if (newFile.fetchError) {
          newFile.errorBody = this.fetchErrorBody || this.defaultErrorBody;
          newFile.errorSubject =
            this.fetchErrorHeader || this.defaultErrorHeader;
          newFile.invalid = true;
        } else if (newFile.invalidFileType) {
          newFile.errorBody =
            this.invalidFileTypeErrorBody || this.defaultErrorBody;
          newFile.errorSubject =
            this.invalidFileTypeErrorHeader || this.defaultErrorHeader;
          newFile.invalid = true;
        } else if (
          this.maxFileSize &&
          (newFile?.fileSize ?? 0) > this.maxFileSize
        ) {
          newFile.errorBody =
            this.maxFileSizeErrorBody || this.defaultErrorBody;
          newFile.errorSubject =
            this.maxFileSizeErrorHeader || this.defaultErrorHeader;
          newFile.invalid = true;
        }
        return newFile;
      });

      this.files = [...updatedFiles];
      this.fileStatusString = `${this.files.filter((f) => !f.invalid).length} / ${this.files.length} ${this.fileUploadLabel}`;
    };

    const onAddFile = (evt) => {
      const addedFiles = evt.detail.addedFiles;
      evt.stopPropagation();
      updateFiles(addedFiles);
    };

    const onRemoveFile = (_evt, uuid) => {
      this.files = this.files.filter((f) => f.uuid !== uuid);
    };

    const inputHandler = (evt) => {
      this.importUrl = evt.target.value;
    };

    const onCloseHandler = () => {
      this.files = [];
      this.importUrl = '';
    };

    const handleImportFile = () => {
      fetchFile(this.importUrl);
    };

    const numberOfFiles = this.files.length;
    const numberOfValidFiles = this.files.filter(
      (f: FileType) => !f.invalid
    ).length;
    const hasFiles = numberOfFiles > 0;
    const primaryButtonDisabled = !hasFiles || !(numberOfValidFiles > 0);
    const importButtonDisabled = !this.importUrl || hasFiles;
    return html`
      <style>
        ${styles}
      </style>
      <cds-button
        kind="primary"
        @click=${() => modalRef?.setAttribute('open', '')}
      >
        Launch Modal
      </cds-button>
      <cds-modal
        class=${blockClass}
        size="sm"
        ?open=${this.open}
        ${ref((el) => (modalRef = el as HTMLElement))}
        @cds-modal-closed=${() => {
          modalRef?.removeAttribute('open');
          onCloseHandler();
        }}
      >
        <cds-modal-header>
          <cds-modal-heading>${this.title}</cds-modal-heading>
        </cds-modal-header>
        <cds-modal-body class=${`${blockClass}__body-container`}>
          <cds-modal-body-content description>
            ${this.description}
          </cds-modal-body-content>
          <cds-file-uploader label-title=${this.fileDropHeader}>
            <cds-file-uploader-drop-container
              accept=${this.accept}
              ?disabled=${hasFiles}
              @cds-file-uploader-drop-container-changed=${(evt) =>
                onAddFile(evt)}
            >
              ${this.fileDropLabel}
            </cds-file-uploader-drop-container>
          </cds-file-uploader>
          ${this.inputLabel &&
          html`<p class=${`${blockClass}__label`}>${this.inputLabel}</p>`}
          <cds-form-item class=${`${blockClass}__input-group`}>
            <cds-text-input
              placeholder=${this.inputPlaceholder}
              label=""
              id=${this.inputId}
              .value=${this.importUrl}
              @input="${inputHandler}"
              ?disabled=${hasFiles}
            ></cds-text-input>
            <cds-button
              class=${`${blockClass}__import-button`}
              .kind="primary"
              size="sm"
              .type="Submit"
              ?disabled=${importButtonDisabled}
              @click=${handleImportFile}
            >
              ${this.inputButtonIcon ? Add16({ slot: 'icon' }) : ''}
              ${this.inputButtonText}
            </cds-button>
          </cds-form-item>

          <div class="${blockClass}__file-container cds--file-container">
            ${hasFiles
              ? html`<p class=${`${blockClass}__helper-text`}>
                  ${this.fileStatusString}
                </p>`
              : null}
            ${this.files.map(
              (file) => html`
                <cds-file-uploader-item
                  name=${file.name}
                  class=${`${blockClass}__file-uploader-item`}
                  size="lg"
                  state=${file.status}
                  icon-description=${file.iconDescription}
                  ?invalid=${file.invalid === true}
                  error-subject=${file.errorSubject || ''}
                  error-body=${file.errorBody || ''}
                  uuid=${file.uuid}
                  @cds-file-uploader-item-deleted=${(evt) =>
                    onRemoveFile(evt, file.uuid)}
                  >${file.name}</cds-file-uploader-item
                >
              `
            )}
          </div>
        </cds-modal-body>
        <cds-modal-footer>
          <cds-modal-footer-button
            kind="secondary"
            data-modal-close
            @click=${() => {
              onCloseHandler;
            }}
            >${this.secondaryButtonText}</cds-modal-footer-button
          >
          <cds-modal-footer-button
            ?disabled=${primaryButtonDisabled}
            @click=${this.submitHandler}
            >${this.primaryButtonText}</cds-modal-footer-button
          >
        </cds-modal-footer>
      </cds-modal>
    `;
  }

  static styles = styles;
}
export default ImportModal;

// packages/ibm-products/src/components/ImportModal/ImportModal.tsx
/**
 * Copyright IBM Corp. 2021, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  Button,
  ComposedModal,
  FileUploaderDropContainer,
  FileUploaderItem,
  ModalBody,
  ModalFooter,
  ModalHeader,
  TextInput,
  usePrefix,
} from '@carbon/react';
import React, { ForwardedRef, ReactNode, forwardRef, useState } from 'react';

import { Add } from '@carbon/react/icons';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { getDevtoolsProps } from '../../global/js/utils/devtools';
import { pkg } from '../../settings';
import { usePortalTarget } from '../../global/js/hooks/usePortalTarget';
import uuidv4 from '../../global/js/utils/uuidv4';

const componentName = 'ImportModal';

type FileType = {
  fetchError?: undefined | boolean;
  fileData?: File;
  fileSize?: number;
  iconDescription?: string;
  invalidFileType?: boolean;
  name: string;
  status?: 'uploading' | 'edit' | 'complete';
  uuid?: string;
  invalid?: boolean;
  errorBody?: string;
  errorSubject?: string;
};

export interface ImportModalProps {
  /**
   * Specifies the file types that are valid for importing
   */
  accept?: string[];
  /**
   * Optional class name
   */
  className?: string;
  /**
   * The default message shown for an import error
   */
  defaultErrorBody: string;
  /**
   * The default header that is displayed to show an error message
   */
  defaultErrorHeader: string;
  /**
   * Content that is displayed inside the modal
   */
  description?: string;
  /**
   * Optional error body to display specifically for a fetch error
   */
  fetchErrorBody?: string;
  /**
   * Optional error header to display specifically for a fetch error
   */
  fetchErrorHeader?: string;
  /**
   * Header for the drag and drop box
   */
  fileDropHeader?: string;
  /**
   * Label for the drag and drop box
   */
  fileDropLabel?: string;
  /**
   * Label that appears when a file is uploaded to show number of files (1 / 1)
   */
  fileUploadLabel?: string;
  /**
   * Button icon for import by url button
   */
  inputButtonIcon?: boolean;
  /**
   * Button text for import by url button
   */
  inputButtonText: string;
  /**
   * ID for text input
   */
  inputId?: string;
  /**
   * Header to display above import by url
   */
  inputLabel: string;
  /**
   * Placeholder for text input
   */
  inputPlaceholder?: string;
  /**
   * Optional error message to display specifically for a invalid file type error
   */
  invalidFileTypeErrorBody?: string;
  /**
   * Optional error header to display specifically for a invalid file type error
   */
  invalidFileTypeErrorHeader?: string;
  /**
   * Description for delete file icon
   */
  invalidIconDescription?: string;
  /**
   * File size limit in bytes
   */
  maxFileSize?: number;
  /**
   * Optional error message to display specifically for a max file size error
   */
  maxFileSizeErrorBody?: string;
  /**
   * Optional error header to display specifically for a max file size error
   */
  maxFileSizeErrorHeader?: string;
  /**
   * Specify a handler for closing modal
   */
  onClose?(): void;
  /**
   * Specify a handler for "submitting" modal. Access the imported file via `file => {}`
   */
  onRequestSubmit(files: FileType[]): void;
  /**
   * Specify whether the Modal is currently open
   */
  open: boolean;
  /**
   * The DOM node the tearsheet should be rendered within. Defaults to document.body.
   */
  portalTarget?: ReactNode;
  /**
   * Specify the text for the primary button
   */
  primaryButtonText: string;
  /**
   * Specify the text for the secondary button
   */
  secondaryButtonText: string;
  /**
   * The text displayed at the top of the modal
   */
  title: string;
}

export const ImportModal: React.FC<ImportModalProps> = forwardRef(
  (
    {
      // The component props, in alphabetical order (for consistency).

      accept = [],
      className,
      defaultErrorBody,
      defaultErrorHeader,
      description,
      fetchErrorBody,
      fetchErrorHeader,
      fileDropHeader,
      fileDropLabel,
      fileUploadLabel,
      inputButtonIcon,
      inputButtonText,
      inputId,
      inputLabel,
      inputPlaceholder,
      invalidFileTypeErrorBody,
      invalidFileTypeErrorHeader,
      invalidIconDescription,
      maxFileSize,
      maxFileSizeErrorBody,
      maxFileSizeErrorHeader,
      onClose,
      onRequestSubmit,
      open,
      portalTarget: portalTargetIn,
      primaryButtonText,
      secondaryButtonText,
      title,

      // Collect any other property values passed in.
      ...rest
    },
    ref: ForwardedRef<HTMLDivElement>
  ) => {
    const carbonPrefix = usePrefix();
    const [files, setFiles] = useState<Array<FileType>>([]);
    const [importUrl, setImportUrl] = useState('');
    const renderPortalUse = usePortalTarget(portalTargetIn);

    const isInvalidFileType = (file) => {
      const acceptSet = new Set(accept);
      const name = file.name;
      const mimeType = file.type;
      const extension = `.${name.split('.').pop()}`;
      if (
        acceptSet.has(mimeType) ||
        acceptSet.has(extension) ||
        accept.length === 0
      ) {
        return false;
      }
      return true;
    };

    const updateFiles = (newFiles) => {
      const updatedFiles = newFiles.map((file) => {
        const newFile = {
          uuid: file.uuid || uuidv4(),
          status: 'edit',
          iconDescription: invalidIconDescription,
          name: file.name,
          fileSize: file.size,
          invalidFileType: file.invalidFileType,
          fileData: file,
          fetchError: file.fetchError,
        } as FileType;
        if (newFile.fetchError) {
          newFile.errorBody = fetchErrorBody || defaultErrorBody;
          newFile.errorSubject = fetchErrorHeader || defaultErrorHeader;
          newFile.invalid = true;
        } else if (newFile.invalidFileType) {
          newFile.errorBody = invalidFileTypeErrorBody || defaultErrorBody;
          newFile.errorSubject =
            invalidFileTypeErrorHeader || defaultErrorHeader;
          newFile.invalid = true;
        } else if (maxFileSize && (newFile?.fileSize ?? 0) > maxFileSize) {
          newFile.errorBody = maxFileSizeErrorBody || defaultErrorBody;
          newFile.errorSubject = maxFileSizeErrorHeader || defaultErrorHeader;
          newFile.invalid = true;
        }
        return newFile;
      });
      const finalFiles = [...updatedFiles];
      setFiles(finalFiles);
    };

    const fetchFile = async (evt) => {
      evt.preventDefault();
      const fileName = importUrl
        .substring(importUrl.lastIndexOf('/') + 1)
        .split('?')[0];
      const pendingFile: FileType = {
        name: fileName,
        status: 'uploading',
        uuid: uuidv4(),
      };
      setFiles([pendingFile]);
      try {
        const response = await fetch(importUrl);
        if (!response.ok || response.status !== 200) {
          throw new Error(`${response.status}`);
        }
        const blob = await response.blob();
        const fetchedFile: FileType = new File([blob], fileName, {
          type: blob.type,
        });
        fetchedFile.invalidFileType = isInvalidFileType(fetchedFile);
        fetchedFile.uuid = pendingFile.uuid;
        updateFiles([fetchedFile]);
      } catch (err) {
        const failedFile = {
          ...pendingFile,
          fetchError: true,
        };
        updateFiles([failedFile]);
      }
    };

    const onAddFile = (evt, { addedFiles }) => {
      evt.stopPropagation();
      updateFiles(addedFiles);
    };

    const onRemoveFile = (uuid) => {
      const updatedFiles = files.filter((f: FileType) => f.uuid !== uuid);
      setFiles(updatedFiles);
    };

    const onSubmitHandler = () => {
      onRequestSubmit(files);
    };

    const inputHandler = (evt) => {
      setImportUrl(evt.target.value);
    };

    const onCloseHandler = () => {
      setFiles([]);
      setImportUrl('');
      if (onClose) {
        onClose();
      }
    };

    const numberOfFiles = files.length;
    const numberOfValidFiles = files.filter((f: FileType) => !f.invalid).length;
    const hasFiles = numberOfFiles > 0;
    const primaryButtonDisabled = !hasFiles || !(numberOfValidFiles > 0);
    const importButtonDisabled = !importUrl || hasFiles;
    const fileStatusString = `${numberOfValidFiles} / ${numberOfFiles} ${fileUploadLabel}`;
    const blockClass = `${pkg.prefix}--import-modal`;

    return renderPortalUse(
      <ComposedModal
        {...rest}
        {...{ open, ref, ...getDevtoolsProps(componentName) }}
        aria-label={title}
        className={cx(blockClass, className)}
        size="sm"
        preventCloseOnClickOutside
        onClose={onCloseHandler}
      >
        <ModalHeader className={`${blockClass}__header`} title={title} />
        <ModalBody className={`${blockClass}__body-container`}>
          {description && (
            <p className={`${blockClass}__body`}>{description}</p>
          )}
          {fileDropHeader && (
            <p className={`${blockClass}__file-drop-header`}>
              {fileDropHeader}
            </p>
          )}
          <FileUploaderDropContainer
            accept={accept}
            labelText={fileDropLabel}
            onAddFiles={onAddFile}
            disabled={hasFiles}
            data-modal-primary-focus
          />
          <div className={`${blockClass}__input-group`}>
            <TextInput
              labelText={<p className={`${blockClass}__label`}>{inputLabel}</p>}
              id={inputId || ''}
              onChange={inputHandler}
              placeholder={inputPlaceholder}
              value={importUrl}
              disabled={hasFiles}
              aria-label={inputLabel}
            />
            <Button
              onClick={fetchFile}
              className={`${blockClass}__import-button`}
              size="md"
              disabled={importButtonDisabled}
              renderIcon={
                inputButtonIcon
                  ? (props) => <Add size={20} {...props} />
                  : undefined
              }
            >
              {inputButtonText}
            </Button>
          </div>
          <div
            className={`${carbonPrefix}--file-container ${blockClass}__file-container`}
          >
            {hasFiles && (
              <p className={`${blockClass}__helper-text`}>{fileStatusString}</p>
            )}
            {files.map((file: FileType) => (
              <FileUploaderItem
                key={file.uuid}
                onDelete={() => onRemoveFile(file.uuid)}
                name={file.name}
                status={file.status}
                size="lg"
                uuid={file.uuid}
                iconDescription={file.iconDescription}
                invalid={file.invalid}
                errorBody={file.errorBody}
                errorSubject={file.errorSubject}
                {...{
                  filesize: file.fileSize /* cspell:disable-line */,
                }}
              />
            ))}
          </div>
        </ModalBody>
        <ModalFooter className={`${blockClass}__footer`}>
          <Button type="button" kind="secondary" onClick={onCloseHandler}>
            {secondaryButtonText}
          </Button>
          <Button
            type="submit"
            kind="primary"
            onClick={onSubmitHandler}
            disabled={primaryButtonDisabled}
          >
            {primaryButtonText}
          </Button>
        </ModalFooter>
      </ComposedModal>
    );
  }
);

// Return a placeholder if not released and not enabled by feature flag

ImportModal.propTypes = {
  /**
   * Specifies the file types that are valid for importing
   */
  accept: PropTypes.array,
  /**
   * Optional class name
   */
  className: PropTypes.string,
  /**
   * The default message shown for an import error
   */
  defaultErrorBody: PropTypes.string.isRequired,
  /**
   * The default header that is displayed to show an error message
   */
  defaultErrorHeader: PropTypes.string.isRequired,
  /**
   * Content that is displayed inside the modal
   */
  description: PropTypes.string,
  /**
   * Optional error body to display specifically for a fetch error
   */
  fetchErrorBody: PropTypes.string,
  /**
   * Optional error header to display specifically for a fetch error
   */
  fetchErrorHeader: PropTypes.string,
  /**
   * Header for the drag and drop box
   */
  fileDropHeader: PropTypes.string,
  /**
   * Label for the drag and drop box
   */
  fileDropLabel: PropTypes.string,
  /**
   * Label that appears when a file is uploaded to show number of files (1 / 1)
   */
  fileUploadLabel: PropTypes.string,
  /**
   * Button icon for import by url button
   */
  inputButtonIcon: PropTypes.bool,
  /**
   * Button text for import by url button
   */
  inputButtonText: PropTypes.string.isRequired,
  /**
   * ID for text input
   */
  inputId: PropTypes.string,
  /**
   * Header to display above import by url
   */
  inputLabel: PropTypes.string.isRequired,
  /**
   * Placeholder for text input
   */
  inputPlaceholder: PropTypes.string,
  /**
   * Optional error message to display specifically for a invalid file type error
   */
  invalidFileTypeErrorBody: PropTypes.string,
  /**
   * Optional error header to display specifically for a invalid file type error
   */
  invalidFileTypeErrorHeader: PropTypes.string,
  /**
   * Description for delete file icon
   */
  invalidIconDescription: PropTypes.string,
  /**
   * File size limit in bytes
   */
  maxFileSize: PropTypes.number,
  /**
   * Optional error message to display specifically for a max file size error
   */
  maxFileSizeErrorBody: PropTypes.string,
  /**
   * Optional error header to display specifically for a max file size error
   */
  maxFileSizeErrorHeader: PropTypes.string,
  /**
   * Specify a handler for closing modal
   */
  onClose: PropTypes.func,
  /**
   * Specify a handler for "submitting" modal. Access the imported file via `file => {}`
   */
  onRequestSubmit: PropTypes.func.isRequired,
  /**
   * Specify whether the Modal is currently open
   */
  open: PropTypes.bool.isRequired,
  /**
   * The DOM node the tearsheet should be rendered within. Defaults to document.body.
   */
  portalTarget: PropTypes.node,
  /**
   * Specify the text for the primary button
   */
  primaryButtonText: PropTypes.string.isRequired,
  /**
   * Specify the text for the secondary button
   */
  secondaryButtonText: PropTypes.string.isRequired,
  /**
   * The text displayed at the top of the modal
   */
  title: PropTypes.string.isRequired,
};

ImportModal.displayName = componentName;
