// packages/ibm-products-web-components/examples/create-full-page/src/components/simple-header.ts
/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { carbonElement as customElement } from '@carbon/web-components/es/globals/decorators/carbon-element';
import '@carbon/web-components/es/components/breadcrumb/index.js';
import styles from './create-full-page.scss?lit';

const blockClass = 'simple-header';

export interface Breadcrumb {
  key?: string;
  label: string;
  href?: string;
  isCurrentPage?: boolean;
}

/**
 * SimpleHeader component for web components
 */
@customElement('simple-header')
export class SimpleHeader extends LitElement {
  /**
   * Page title
   */
  @property({ type: String })
  title = '';

  /**
   * Breadcrumbs array
   */
  @property({ type: Array })
  breadcrumbs: Breadcrumb[] = [];

  /**
   * Whether to show trailing slash in breadcrumbs
   */
  @property({ type: Boolean, attribute: 'no-trailing-slash' })
  noTrailingSlash = true;

  /**
   * Maximum visible breadcrumbs
   */
  @property({ type: Number, attribute: 'max-visible' })
  maxVisible?: number;

  /**
   * Overflow aria label
   */
  @property({ type: String, attribute: 'overflow-aria-label' })
  overflowAriaLabel = 'Open and close additional breadcrumb item list.';

  /**
   * Overflow tooltip alignment
   */
  @property({ type: String, attribute: 'overflow-tooltip-align' })
  overflowTooltipAlign = 'bottom';

  connectedCallback() {
    console.log(this.breadcrumbs);
    
    super.connectedCallback();
    if (!this.title && (!this.breadcrumbs || this.breadcrumbs.length === 0)) {
      console.warn(
        'Warning: You have tried using a SimpleHeader component without specifying a title or breadcrumbs props'
      );
    }
  }

  render() {
    const classes = {
      [blockClass]: true,
    };

    return html`
      <header class="${classMap(classes)}">
        ${this.breadcrumbs && this.breadcrumbs.length > 0
          ? html`
              <breadcrumb-with-overflow
                class="${blockClass}__breadcrumbs"
                .breadcrumbs="${this.breadcrumbs}"
                ?no-trailing-slash="${this.noTrailingSlash}"
                max-visible="${this.maxVisible || ''}"
                overflow-aria-label="${this.overflowAriaLabel}"
                overflow-tooltip-align="${this.overflowTooltipAlign}"
              ></breadcrumb-with-overflow>
            `
          : ''}
        ${this.title
          ? html`
              <h1 class="${blockClass}__title">${this.title}</h1>
            `
          : ''}
      </header>
    `;
  }
  static styles = styles;
}

// packages/ibm-products/src/components/SimpleHeader/SimpleHeader.tsx
/**
 * Copyright IBM Corp. 2023, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import PropTypes from 'prop-types';

import React, { useCallback, useEffect } from 'react';
import cx from 'classnames';
import { pkg } from '../../settings';
import pconsole from '../../global/js/utils/pconsole';
import { BreadcrumbWithOverflow } from '../BreadcrumbWithOverflow';
import { Tooltip, Heading } from '@carbon/react';

const blockClass = `${pkg.prefix}--simple-header`;
const componentName = 'SimpleHeader';
/**
 * The SimpleHeader is not public and only used internally by CreateFullPage.
 *
 * Component varieties:
 * - Header with Breadcrumbs
 * - Header with Title
 * - Header with Breadcrumbs and Title
 *
 *
 * The component will throw a warning message if neither a title or breadcrumbs are provided
 * since it requires at least one of them.
 * */
const SimpleHeader = ({
  breadcrumbs,
  className,
  title,
  noTrailingSlash = true,
  maxVisible,
  overflowAriaLabel,
  overflowTooltipAlign,
  ...rest
}) => {
  const warnIfNoTitleOrBreadcrumbs = useCallback(() => {
    if (!title && !breadcrumbs?.length) {
      pconsole.error(
        `Warning: You have tried using a ${componentName} component without specifying a title or breadcrumbs props`
      );
    }
  }, [breadcrumbs, title]);

  useEffect(() => {
    warnIfNoTitleOrBreadcrumbs();
  }, [title, breadcrumbs, warnIfNoTitleOrBreadcrumbs]);

  return (
    <header className={cx(blockClass, className)} {...rest}>
      {breadcrumbs?.length > 0 && (
        <BreadcrumbWithOverflow
          label=""
          noTrailingSlash={noTrailingSlash}
          className={cx(`${blockClass}__breadcrumbs`)}
          breadcrumbs={breadcrumbs}
          maxVisible={maxVisible}
          overflowAriaLabel={overflowAriaLabel}
          overflowTooltipAlign={overflowTooltipAlign}
        />
      )}
      {title && (
        <Heading className={cx(`${blockClass}__title`)}>{title}</Heading>
      )}
    </header>
  );
};

SimpleHeader.propTypes = {
  /** Header breadcrumbs */
  breadcrumbs: PropTypes.arrayOf(
    PropTypes.shape({
      /** breadcrumb item key */
      key: PropTypes.string.isRequired,
      /** breadcrumb item label */
      label: PropTypes.string.isRequired,
      /** breadcrumb item link */
      href: PropTypes.string,
      /** breadcrumb item title tooltip */
      title: PropTypes.string,
      /** Provide if this breadcrumb item represents the current page */
      isCurrentPage: PropTypes.bool,
    })
  ),

  /** Header classname */
  className: PropTypes.string,

  /**	Maximum visible breadcrumb-items before overflow is used (values less than 1 are treated as 1) */
  maxVisible: PropTypes.number,

  /** A prop to omit the trailing slash for the breadcrumbs */
  noTrailingSlash: PropTypes.bool,

  /** Label for open/close overflow button used for breadcrumb items that do not fit */
  overflowAriaLabel: PropTypes.string,

  /**
   * overflowTooltipAlign: align tooltip position
   */

  overflowTooltipAlign: Tooltip.propTypes.align,
  /** Header title */
  title: PropTypes.string,
};

export { SimpleHeader };
